
import type { Saint } from "../saint-types"
import { LiturgicalColor } from "../../liturgical-types"
import { CelebrationRank } from "../../celebrations/celebrations-types"

// June saints
export const juneGeneralSaints: Saint[] = [
  {
    id: "peter-of-verona",
    name: "St. Peter of Verona",
    feast_day: "06-04",
    short_bio: "Dominican preacher and martyr, known for his defense of Catholic orthodoxy.",
    biography: [
      "St. Peter of Verona, also known as Peter Martyr, was born in Verona, Italy, around 1205 to parents who were members of the Cathar heresy. Despite his heretical upbringing, Peter was drawn to the Catholic faith and entered the Dominican Order at the age of 15 after hearing the preaching of St. Dominic himself. His conversion was a source of great sorrow to his parents, who disowned him, but Peter remained steadfast in his new faith and quickly distinguished himself by his piety, learning, and zeal for souls.",
      "After completing his studies, Peter became one of the most famous preachers of his time, traveling throughout northern and central Italy combating heresy and bringing many back to the Catholic faith. His powerful preaching, combined with his reputation for holiness and miracles, made him a formidable opponent of the Cathar and Patarine heresies. In 1232, he was appointed Inquisitor for northern Italy by Pope Gregory IX, a position that made him many enemies among the heretical sects he sought to convert or suppress.",
      "Peter's work as an inquisitor was marked by both great success and growing danger. He established the Confraternity of the Blessed Virgin Mary (later known as the Society of the Holy Name) to promote devotion to the Holy Name of Jesus and to combat blasphemy. Despite numerous threats against his life, he continued his preaching missions fearlessly, often beginning his sermons with the words, 'Into the peace of Christ let us proceed.' His reputation for holiness was such that it was said he could read souls, and many were converted simply by his presence.",
      "On April 6, 1252, while traveling from Como to Milan, Peter and his companion, Brother Dominic, were ambushed by a group of Cathar assassins led by a man named Carino of Balsamo. Struck on the head with an axe, Peter fell mortally wounded but managed to write the opening words of the Creed in his own blood: 'Credo in Unum Deum' (I believe in one God). With his dying breath, he forgave his murderer, saying, 'May God forgive you, my brother.' This act of forgiveness so moved Carino that he later repented, became a Dominican lay brother, and lived a life of penance.",
      "Peter of Verona was canonized just one year after his death by Pope Innocent IV, making his one of the fastest canonizations in Church history. His tomb in the Basilica of Sant'Eustorgio in Milan became an important pilgrimage site, and he is often depicted in art with a cleaver in his head and a finger to his lips, symbolizing his martyrdom and his defense of the faith. As the first Dominican martyr, he holds a special place in the Order of Preachers and is venerated as the patron saint of inquisitors, midwives, and the Italian cities of Verona and Cremona.",
      "His feast, no longer on the general calendar, is celebrated on June 4th in the Dominican Order.",
    ],
    image_url: "/saints/st-peter-of-verona.jpg",
    patronage: "Inquisitors, midwives, Verona, Cremona",
    birth_year: 1205,
    death_year: 1252,
    prayers:
      "O God, source of all good, you called Saint Peter, glorious martyr, to preach the faith and gave him the grace to lay down his life for it. Through his intercession, grant that we may be strengthened in faith and love and may bear witness to the truth of the Gospel by the way we live. We ask this through our Lord Jesus Christ, your Son, who lives and reigns with you and the Holy Spirit, one God, for ever and ever. Amen.",
    is_dominican: true,
    rank: CelebrationRank.OPTIONAL_MEMORIAL,
    color: LiturgicalColor.RED,
    proper: "Common of One Martyr",
  },
  {
    id: "marcellinus-and-peter",
    name: "Sts. Marcellinus and Peter",
    feast_day: "06-02",
    short_bio: "Early Roman martyrs venerated since the 4th century.",
    biography: [
      "Sts. Marcellinus and Peter were Roman martyrs who suffered during the Diocletian persecution in the early 4th century. Marcellinus was a priest, and Peter was an exorcist in the Roman Church. Their martyrdom was particularly notable and became widely venerated in the early Christian community. The exact details of their lives are scarce, but their martyrdom was well-documented by early Christian writers.",
      "According to tradition, Marcellinus and Peter were arrested during the persecution of Diocletian around 304 AD. They were imprisoned and subjected to various tortures for their refusal to renounce their Christian faith. Despite the severe treatment, they remained steadfast in their beliefs, offering encouragement to their fellow prisoners and even converting their jailer and his family to Christianity.",
      "The two saints were eventually beheaded in a forest outside Rome to prevent Christians from venerating their remains. However, two Christian women, Lucilla and Firmina, discovered their bodies and gave them a proper burial in the Catacombs of Marcellinus and Peter on the Via Labicana. Their tomb became an important place of pilgrimage, and a basilica was later built over the site by Emperor Constantine the Great at the request of his mother, St. Helena.",
      "The veneration of Marcellinus and Peter spread quickly throughout the Christian world. Their names were included in the Roman Canon (Eucharistic Prayer I) of the Mass, where they are still mentioned today. Pope Damasus I, who was particularly devoted to the early martyrs, composed an epitaph in their honor, which was placed near their tomb in the catacombs.",
    ],
    image_url: "/saints/sts-marcellinus-and-peter.jpg",
    patronage: "Cobblers, torture victims, those suffering from demonic possession",
    birth_year: null,
    death_year: 304,
    prayers:
      "O God, who gladden us each year with the feast day of the martyrs Saints Marcellinus and Peter, grant that we may be helped by their merits as we are enlightened by the example of their godly life. Through our Lord Jesus Christ, your Son, who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    is_dominican: false,
    rank: CelebrationRank.OPTIONAL_MEMORIAL,
    color: LiturgicalColor.RED,
    proper: "Common of Martyrs",
  },
  {
    id: "charles-lwanga-companions",
    name: "St. Charles Lwanga and Companions",
    feast_day: "06-03",
    short_bio: "Ugandan martyrs who gave their lives for Christ in the late 19th century.",
    biography: [
      "St. Charles Lwanga and his companions were a group of 22 Ugandan converts to Catholicism who were martyred between 1885 and 1887 during the reign of King Mwanga II of Buganda. These martyrs included both Roman Catholic and Anglican converts, with the Catholic Church canonizing 22 of them on October 18, 1964, during the Second Vatican Council. Their martyrdom represents one of the most significant moments in the history of the African Church and stands as a powerful witness to the strength of faith in the face of persecution.",
      "Charles Lwanga, the most prominent among the martyrs, was born in the Kingdom of Buganda (modern-day Uganda) around 1860. He served as the chief of the royal pages and was a catechist in the Catholic mission. When King Mwanga II began persecuting Christians, Charles took it upon himself to protect the young pages in his care, baptizing several of them himself. His leadership and courage in the face of danger made him a central figure in the Christian community at the royal court.",
      "The persecution began when King Mwanga, who had initially tolerated Christian missionaries, grew increasingly hostile to the new religion. The Christians' refusal to participate in the king's immoral practices and their rejection of traditional religious customs angered Mwanga. The situation reached a crisis point when the king ordered the execution of Joseph Mukasa, a Catholic catechist and advisor to the king, for opposing the execution of an Anglican missionary. This marked the beginning of a systematic persecution of Christians in the kingdom.",
      "On June 3, 1886, Charles Lwanga and 12 companions were burned to death at Namugongo for refusing to renounce their Christian faith. The execution was particularly brutal, with the martyrs being wrapped in reed mats and slowly burned alive. Charles famously encouraged his companions during their ordeal, saying, 'You are burning me, but it is as if you are pouring water over my body.' Their courage and faith in the face of such suffering inspired many others to embrace Christianity.",
      "The witness of Charles Lwanga and his companions had a profound impact on the spread of Christianity in Africa. Despite the persecution, the Church in Uganda grew rapidly after their deaths. Today, the Uganda Martyrs are venerated throughout Africa and around the world as powerful examples of faith and courage. The site of their martyrdom at Namugongo has become a major pilgrimage destination, with millions of Christians visiting each year to honor their memory and seek their intercession.",
      "The legacy of the Ugandan martyrs extends far beyond their historical moment. They represent the universal call to holiness and the power of faith to transform societies. Their feast day on June 3rd is a national holiday in Uganda and is celebrated with great solemnity. The Catholic Church holds them up as models of evangelization, showing how the Gospel can take root in any culture and bear abundant fruit, even in the face of violent opposition.",
    ],
    image_url: "/saints/st-charles-lwanga-companions.jpg",
    patronage: "African Catholic Youth Action, converts, torture victims",
    birth_year: 1860,
    death_year: 1886,
    prayers:
      "O God, who have made the blood of Martyrs the seed of Christians, mercifully grant that the field which is your Church, watered by the blood shed by Saints Charles Lwanga and his companions, may be fertile and always yield you an abundant harvest. Through our Lord Jesus Christ, your Son, who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    is_dominican: false,
    rank: CelebrationRank.MEMORIAL,
    color: LiturgicalColor.RED,
    proper: "Common of Several Martyrs",
  },
  {
    id: "justin-martyr",
    name: "St. Justin Martyr",
    feast_day: "06-01",
    short_bio: "Early Christian apologist who reconciled Greek philosophy with Christian faith.",
    biography: [
      "St. Justin Martyr was born around 100 AD in Flavia Neapolis (modern-day Nablus in the West Bank), to pagan Greek parents, receiving a thorough education in rhetoric, poetry, and history before developing a passionate interest in philosophy, which he viewed as the path to truth and the knowledge of God.",
      "He studied various philosophical schools—Stoicism, Aristotelianism, Pythagoreanism, and Platonism—but found them ultimately unsatisfying until a chance meeting with an old man by the sea who introduced him to the Hebrew prophets and Christian revelation, which Justin recognized as the true philosophy he had been seeking.",
      "After his conversion to Christianity around 130 AD, Justin continued to wear his philosopher's cloak, seeing no contradiction between his philosophical pursuits and his new faith, and established a school in Rome where he engaged in debates with pagans, Jews, and heretics, using his philosophical training to defend Christianity through rational arguments.",
      "Justin authored several important apologetical works, including two \"Apologies\" addressed to the Roman emperors Antoninus Pius and Marcus Aurelius, as well as the \"Dialogue with Trypho the Jew,\" in which he used both philosophy and the Hebrew Scriptures to argue for the truth of Christianity and to defend Christians against false accusations.",
      "His writings provide valuable historical information about early Christian liturgical practices, including detailed descriptions of Baptism and the Eucharist, which he boldly shared despite the \"discipline of the secret\" that normally kept such practices hidden from non-Christians.",
      "Justin was particularly significant for developing the concept of the \"Logos\" (Word) as a bridge between Greek philosophy and Christian revelation, arguing that Christ is the Logos incarnate, and that the \"seeds of the Word\" (logos spermatikos) were present in the works of pre-Christian philosophers and poets.",
      "In 165 AD, during the persecution under Emperor Marcus Aurelius, Justin was arrested along with six companions, and when ordered by the prefect Rusticus to sacrifice to the Roman gods, he refused, stating, \"No one who is right-thinking stoops from true worship to false worship,\" leading to his beheading and subsequent veneration as one of the most important early Christian martyrs and intellectuals."
    ],
    image_url: "/saints/st-justin-martyr.jpg",
    patronage: "Philosophers, apologists, lecturers, speakers",
    birth_year: 100,
    death_year: 165,
    prayers:
      "O God, who through the folly of the Cross wondrously taught Saint Justin the Martyr the surpassing knowledge of Jesus Christ, grant us, through his intercession, that, having rejected deception and error, we may become steadfast in the faith. Through our Lord Jesus Christ, your Son, who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    is_dominican: false,
    rank: CelebrationRank.MEMORIAL,
    color: LiturgicalColor.RED,
    proper: "Proper of Saints",
  },
  {
    id: "norbert",
    name: "St. Norbert",
    feast_day: "06-06",
    short_bio: "Founder of the Premonstratensian Order and reformer of clergy.",
    biography: [
      "St. Norbert was born around 1080 in Xanten, Germany, to Heribert, Count of Gennep, a member of the high nobility with connections to the imperial court, and grew up in an environment of wealth and privilege, eventually becoming a subdeacon and receiving benefices at the churches of St. Victor in Xanten and St. Peter's in Cologne.",
      "Despite his clerical status, Norbert lived a worldly lifestyle at the courts of the Archbishop of Cologne and Emperor Henry V, enjoying luxury and pleasures until 1115, when he narrowly escaped death during a violent thunderstorm while riding his horse—an experience he interpreted as a divine call to conversion, similar to St. Paul's experience on the road to Damascus.",
      "Following his conversion, Norbert spent three years in penance and prayer, studying for the priesthood under the guidance of Benedictine monks at the Abbey of Siegburg, and after being ordained, he attempted to reform the canons of Xanten but was rejected, leading him to give away his possessions and begin the life of an itinerant preacher.",
      "In 1120, with the approval of Pope Callistus II, Norbert established a community in Prémontré, France, which became the foundation of the Canons Regular of Prémontré (the Premonstratensians or Norbertines), following the Rule of St. Augustine with an emphasis on austerity, prayer, preaching, and pastoral care.",
      "Norbert was a strong defender of the Eucharist against heretical teachings, particularly against Tanchelm of Antwerp who denied the real presence of Christ, and he promoted Eucharistic adoration as an essential element of Christian spirituality, earning him the title \"Apostle of the Blessed Sacrament.\"",
      "In 1126, against his wishes, Norbert was appointed Archbishop of Magdeburg by Emperor Lothair III and the papal legate, a position he used to reform the clergy, recover alienated church properties, and champion papal authority against imperial claims during the Investiture Controversy.",
      "St. Norbert died on June 6, 1134, in Magdeburg, Germany, was canonized by Pope Gregory XIII in 1582, and his relics were later transferred to Strahov Abbey in Prague, where they remain to this day, while his legacy continues through the Norbertine Order which maintains its commitment to contemplative prayer, community life, and active ministry."
    ],
    image_url: "/saints/st-norbert.jpg",
    patronage: "Bohemia, Czech Republic, peace, expectant mothers",
    birth_year: 1080,
    death_year: 1134,
    prayers:
      "O God, who made the Bishop Saint Norbert a servant of your Church outstanding in his prayer and pastoral zeal, grant, we ask, that by the help of his intercession, the flock of the faithful may always find shepherds after your own heart and be fed in the pastures of salvation. Through our Lord Jesus Christ, your Son, who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    is_dominican: false,
    rank: CelebrationRank.OPTIONAL_MEMORIAL,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },
  {
    id: "anthony-of-padua",
    name: "St. Anthony of Padua",
    feast_day: "06-13",
    short_bio: "Franciscan friar known for his powerful preaching and miracles.",
    biography: [
      "St. Anthony was born Fernando Martins de Bulhões in Lisbon, Portugal, on August 15, 1195, to a wealthy and noble family, and at the age of 15, he joined the Canons Regular of St. Augustine, first at São Vicente de Fora in Lisbon, then at Santa Cruz Monastery in Coimbra, where he studied theology and Latin and was ordained a priest.",
      "In 1220, deeply moved by the martyrdom of five Franciscan friars who had been preaching to Muslims in Morocco, Fernando obtained permission to leave the Augustinians and join the new Franciscan Order, taking the name Anthony and setting sail for Morocco himself with the intention of becoming a martyr for the faith.",
      "Shortly after arriving in Morocco, Anthony became seriously ill and was forced to return to Portugal, but his ship was blown off course by a violent storm and landed in Sicily, from where he traveled to Assisi and participated in the famous Pentecost Chapter of Mats in 1221, where he met St. Francis of Assisi.",
      "Anthony's exceptional knowledge of theology and Scripture remained hidden until a certain occasion when he was called unexpectedly to preach at an ordination ceremony, delivering such a moving and eloquent sermon that his superiors immediately appointed him as the order's first theology teacher and sent him to preach against heresy in northern Italy and southern France.",
      "Known for his profound knowledge of Scripture, forceful preaching, and numerous miracles, Anthony became one of the most quickly canonized saints in church history when Pope Gregory IX declared him a saint on May 30, 1232, less than a year after his death, calling him the \"Ark of the Testament\" and the \"Repository of Holy Scripture.\"",
      "Though commonly associated with Padua, Italy, where he spent the final years of his life, Anthony actually spent very little time there—arriving in the city in 1227, then leaving for a period to serve as Provincial Superior of northern Italy, and finally returning in 1230, just months before his death in 1231.",
      "St. Anthony is widely invoked as the patron saint of lost articles, with the tradition originating from an incident when a novice stole a valuable psalter from him, prompting Anthony to pray for its return, after which the thief experienced terrifying visions and not only returned the book but also rejoined the order."
    ],
    image_url: "/saints/st-anthony-of-padua.jpg",
    patronage: "Lost items, poor people, sailors, travelers, elderly, oppressed people",
    birth_year: 1195,
    death_year: 1231,
    prayers:
      "Almighty ever-living God, who gave Saint Anthony of Padua to your people as an outstanding preacher and an intercessor in their need, grant that, with his assistance, as we follow the teachings of the Christian life, we may know your help in every trial. Through our Lord Jesus Christ, your Son, who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    is_dominican: false,
    rank: CelebrationRank.MEMORIAL,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },
  {
    id: "john-fisher",
    name: "St. John Fisher",
    feast_day: "06-22",
    short_bio: "English bishop and cardinal who was martyred for opposing Henry VIII's divorce.",
    biography: [
      "St. John Fisher was born in Beverley, Yorkshire, England, in 1469, the eldest son of Robert and Agnes Fisher, and after his father's death, his mother ensured he received an excellent education at the local grammar school before he entered Cambridge University at the age of 14, where he excelled in his studies and was ordained a priest around 1491.",
      "Fisher's intellectual brilliance and deep piety brought him to the attention of Lady Margaret Beaufort, mother of King Henry VII, who appointed him her confessor and chaplain, and whose generous endowments helped Fisher establish Christ's College and St. John's College at Cambridge, significantly advancing the university's reputation.",
      "In 1504, at the unusually young age of 35, Fisher was appointed Bishop of Rochester, the poorest diocese in England, which he chose never to leave despite offers of wealthier sees, devoting himself to pastoral care, university reform, and scholarly work, including writings against the emerging Protestant teachings of Martin Luther.",
      "When King Henry VIII sought to annul his marriage to Catherine of Aragon in order to marry Anne Boleyn, Fisher became the queen's chief supporter and defender, arguing that the marriage was valid and could not be dissolved by any earthly power, directly challenging the king's desires and setting himself on a collision course with the monarch.",
      "After refusing to take the Oath of Supremacy, which acknowledged Henry as Supreme Head of the Church of England, Fisher was imprisoned in the Tower of London in April 1534, where despite his advanced age and deteriorating health, he maintained his position that the Pope alone was the successor of St. Peter and head of the Church.",
      "While in prison, Pope Paul III created Fisher a cardinal on May 20, 1535, which rather than helping his cause, further enraged King Henry, who reportedly declared that Fisher would never live to receive the cardinal's hat, and hastened the bishop's trial for treason.",
      "On June 22, 1535, John Fisher was beheaded on Tower Hill, his last words being a declaration of faith and a prayer for the king's soul, and his head was displayed on London Bridge for two weeks before being thrown into the River Thames—making him, along with his friend Sir Thomas More, one of the most prominent English martyrs of the Reformation period."
    ],
    image_url: "/saints/st-john-fisher.jpg",
    patronage: "Diocese of Rochester, education, bishops, academics",
    birth_year: 1469,
    death_year: 1535,
    prayers:
      "O God, who in martyrdom have brought true faith to its highest expression, graciously grant that, strengthened through the intercession of Saint John Fisher, we may confirm by the witness of our life the faith we profess with our lips. Through our Lord Jesus Christ, your Son, who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    is_dominican: false,
    rank: CelebrationRank.OPTIONAL_MEMORIAL,
    color: LiturgicalColor.RED,
    proper: "Proper of Saints",
  },
  {
    id: "irenaeus-lyon",
    name: "St. Irenaeus of Lyon",
    feast_day: "06-28",
    short_bio: "Early Church Father and apologist who defended orthodox Christianity against Gnosticism.",
    biography: [
      "St. Irenaeus was born around 130 AD in Smyrna (modern-day Izmir, Turkey), where as a young man he became a disciple of St. Polycarp, who himself had been a disciple of the Apostle John, thus providing Irenaeus with a direct connection to the apostolic teaching and making him a crucial link in the chain of early Christian tradition.",
      "Around 177 AD, while Irenaeus was away on a mission to Rome, a severe persecution broke out in Lyon (then called Lugdunum) in Gaul, where he was a priest, resulting in the martyrdom of many Christians, including the bishop, St. Pothinus; upon his return, Irenaeus was elected as the new bishop of Lyon, a position he would hold until his death.",
      "As bishop, Irenaeus faced the challenging spread of Gnosticism, a complex set of heretical beliefs that claimed salvation came through secret knowledge (gnosis), portrayed the material world as evil, denied the incarnation of Christ, and rejected the Old Testament God as inferior or even malevolent.",
      "In response to the Gnostic threat, Irenaeus composed his most famous work, \"Against Heresies\" (Adversus Haereses), a five-volume refutation of Gnostic teachings that not only detailed and criticized their complex systems but also presented a comprehensive exposition of orthodox Christian doctrine based on Scripture and apostolic tradition.",
      "Irenaeus developed important theological concepts that remain foundational to Christian theology, including the unity of the Old and New Testaments, the parallel between Adam and Christ (and Eve and Mary), the four-fold gospel canon, and most significantly, his understanding of apostolic succession as the guarantee of authentic Christian teaching.",
      "Beyond his anti-heretical writings, Irenaeus was known as a peace-maker who once intervened with Pope Victor I to prevent the excommunication of churches in Asia Minor over a dispute about the date of Easter, arguing that unity in essential matters should allow for diversity in non-essential practices.",
      "Though traditional accounts suggest Irenaeus died as a martyr around 202 AD during the persecution under Emperor Septimius Severus, historical evidence for this is limited, and he may have died of natural causes; nevertheless, his feast day is celebrated on June 28, and in 2022, Pope Francis declared him a Doctor of the Church with the title \"Doctor unitatis\" (Doctor of Unity)."
    ],
    image_url: "/saints/st-irenaeus.jpg",
    patronage: "Lyon, apologists, catechists, unity of Eastern and Western Churches",
    birth_year: 130,
    death_year: 202,
    prayers:
      "O God, who called the Bishop Saint Irenaeus to confirm true doctrine and the peace of the Church, grant, we pray, through his intercession, that, being renewed in faith and charity, we may always be intent on fostering unity and concord. Through our Lord Jesus Christ, your Son, who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    is_dominican: false,
    rank: CelebrationRank.MEMORIAL,
    color: LiturgicalColor.RED,
    proper: "Proper of Saints",
  },
  {
    id: "first-martyrs-rome",
    name: "First Martyrs of the Church of Rome",
    feast_day: "06-30",
    short_bio: "Christians who were martyred under Emperor Nero following the Great Fire of Rome.",
    biography: [
      "The First Martyrs of the Church of Rome were the Christians who were killed in the persecution that followed the Great Fire of Rome, which broke out on July 19, 64 AD, and raged for six days, destroying much of the city and leaving many homeless and desperate for someone to blame.",
      "Emperor Nero, who was widely suspected of having started the fire himself to clear land for his grand building projects, deflected blame onto the Christians, a relatively new religious group that was already viewed with suspicion due to their refusal to worship the Roman gods and their seemingly secretive practices, making them convenient scapegoats for the disaster.",
      "The Roman historian Tacitus, though not a Christian himself, recorded in his Annals that Nero \"inflicted the most exquisite tortures\" on the Christians, who were \"covered with the skins of beasts and torn by dogs, or were fastened to crosses and set on fire to serve as torches by night\"—public spectacles of cruelty designed to entertain crowds at Nero's gardens and the Circus.",
      "These martyrs came from all walks of Roman society—Jews and Gentiles, slaves and free persons, men and women—and included people who had been converted directly by the apostles Peter and Paul, who were also martyred during this persecution, though they are commemorated separately due to their prominence.",
      "Unlike later persecutions that were empire-wide and systematic attempts to eradicate Christianity through legal means, Nero's persecution was localized to Rome and was more a matter of personal cruelty and political expediency than religious policy, yet it set a precedent for the treatment of Christians as enemies of the state.",
      "The courage of these early martyrs, who chose death rather than denying Christ or offering even token sacrifices to the Roman gods or the emperor's genius, greatly impressed their contemporaries, with Tertullian later observing that \"the blood of martyrs is the seed of the Church\"—noting how their witness led to more conversions rather than destroying the faith.",
      "While many of these martyrs remain anonymous, their collective feast has been celebrated since early times, and Pope Paul VI established June 30 as their official commemoration in the Roman Calendar, placing it immediately after the Solemnity of Saints Peter and Paul to emphasize the connection between the apostolic founders of the Roman Church and the ordinary faithful who followed their example of ultimate sacrifice for the faith."
    ],
    image_url: "/saints/first-martyrs-rome.jpg",
    patronage: "Persecuted Christians, the city of Rome",
    birth_year: null,
    death_year: 64,
    prayers:
      "O God, who consecrated the abundant first fruits of the Roman Church by the blood of the Martyrs, grant, we pray, that with firm courage we may together draw strength from so great a struggle and ever rejoice at the triumph of faithful love. Through our Lord Jesus Christ, your Son, who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    is_dominican: false,
    rank: CelebrationRank.OPTIONAL_MEMORIAL,
    color: LiturgicalColor.RED,
    proper: "Proper of Saints",
  },
]
