import type { Saint } from "../saint-types"
import { LiturgicalColor } from "../../liturgical-types"
import { CelebrationRank } from "../../celebrations/celebrations-types"

// Ancient Doctors of the Church (1st-6th centuries)
export const ancientDoctors: Saint[] = [
  // Add ancient doctors here - this would include figures like:
  // St. Athanasius, St. Basil the Great, St. John Chrysostom, etc.
  // For now, keeping this array empty as the original file structure
  // needs to be analyzed to properly categorize existing doctors
  {
    id: "augustine-of-hippo",
    name: "St. Augustine of Hippo",
    feast_day: "08-28",
    short_bio: "Bishop, theologian, and Doctor of the Church",
    biography: [
      "St. Augustine was born in 354 in Thagaste, North Africa (modern-day Algeria), to a Christian mother, St. Monica, and a pagan father. Despite his mother's influence, Augustine led a hedonistic lifestyle in his youth.",
      "He received an excellent education in rhetoric and became a teacher of rhetoric in Carthage, Rome, and Milan. During this time, he explored various philosophical systems, including Manichaeism and Neoplatonism.",
      "In Milan, influenced by St. Ambrose's preaching and his mother's prayers, Augustine underwent a profound conversion. After hearing a child's voice saying 'Take and read,' he opened the Bible to Romans 13:13-14, which spoke directly to his situation.",
      "He was baptized by St. Ambrose in 387 and returned to Africa, where he established a monastic community. In 391, he was ordained a priest, and in 395, he became Bishop of Hippo, a position he held until his death.",
      "Augustine was a prolific writer whose works have profoundly influenced Western theology and philosophy. His major works include 'Confessions,' an autobiographical account of his conversion; 'City of God,' written after the sack of Rome; and 'On the Trinity.'",
      "He died on August 28, 430, during the Vandal siege of Hippo. He was declared a Doctor of the Church in 1298 by Pope Boniface VIII.",
    ],
    image_url: "/saints/st-augustine.jpg",
    patronage: "Theologians, printers, brewers, those with eye problems",
    birth_year: 354,
    birth_place: "Thagaste, Numidia (modern-day Souk Ahras, Algeria)",
    death_year: 430,
    death_place: "Hippo Regius, Numidia (modern-day Annaba, Algeria)",
    canonization_date: "1298-10-04",
    quotes: [
      "You have made us for yourself, O Lord, and our hearts are restless until they rest in you.",
      "To fall in love with God is the greatest romance; to seek Him the greatest adventure; to find Him, the greatest human achievement.",
      "The world is a book, and those who do not travel read only a page.",
      "Faith is to believe what you do not see; the reward of this faith is to see what you believe.",
      "Love the sinner and hate the sin.",
      "Pray as though everything depended on God. Work as though everything depended on you.",
      "The truth is like a lion; you don't have to defend it. Let it loose; it will defend itself.",
      "If you believe what you like in the gospels, and reject what you don't like, it is not the gospel you believe, but yourself.",
      "God loves each of us as if there were only one of us.",
      "The measure of love is to love without measure.",
      "There is no saint without a past, no sinner without a future.",
      "God provides the wind, but man must raise the sails.",
      "Patience is the companion of wisdom.",
      "The purpose of all wars, is peace.",
      "Miracles are not contrary to nature, but only contrary to what we know about nature."
    ],
    prayers:
      "Renew in your Church, we pray, O Lord, the spirit with which you endowed your Bishop Saint Augustine that, filled with the same spirit, we may thirst for you, the sole fount of true wisdom, and seek you, the author of heavenly love. Through our Lord Jesus Christ, your Son, who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    books: ["confessions", "city-of-god", "on-the-trinity"],
    is_dominican: false,
    is_doctor: true,
    rank: CelebrationRank.FEAST,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },
  {
    id: "ambrose",
    name: "St. Ambrose",
    feast_day: "12-07",
    short_bio: "Bishop of Milan and one of the four original Doctors of the Church",
    biography: [
      "St. Ambrose was born around 340 in Trier, Germany, to a Roman Christian family. His father was the Praetorian Prefect of Gaul. After his father's death, Ambrose moved to Rome with his mother and siblings.",
      "He received an excellent education in literature, law, and rhetoric, and began his career as a lawyer. He was appointed governor of Liguria and Emilia, with headquarters in Milan, around 370.",
      "In 374, when the bishop of Milan died, a contentious dispute broke out between the Nicene and Arian factions over who would succeed him. Ambrose, still a catechumen and not yet baptized, went to the basilica to mediate. While he was speaking, a child cried out, 'Ambrose, bishop!' The crowd took up the chant, and despite his protests, Ambrose was chosen as bishop.",
      "Within a week, Ambrose was baptized, ordained, and consecrated bishop of Milan. He immediately gave away his wealth to the poor and began an intense study of theology to make up for his lack of formal religious training.",
      "Ambrose became a powerful advocate for the Church, defending orthodox Christianity against Arianism. He famously stood up to Emperor Theodosius I, refusing him entry to the basilica after the emperor ordered a massacre in Thessalonica, and requiring him to do public penance.",
      "He was a prolific writer and preacher, composing hymns, biblical commentaries, and theological treatises. His preaching was instrumental in the conversion of St. Augustine of Hippo, who heard Ambrose preach while in Milan.",
      "Ambrose died on April 4, 397, and was buried in the Basilica of Sant'Ambrogio in Milan. He was declared one of the four original Doctors of the Church by Pope Boniface VIII in 1298, along with Augustine, Jerome, and Gregory the Great.",
    ],
    image_url: "/saints/st-ambrose.jpg",
    patronage: "Beekeepers, bees, candle makers, domestic animals, learning, Milan, students",
    birth_year: 340,
    birth_place: "Augusta Treverorum, Gallia Belgica, Roman Empire (modern-day Trier, Germany)",
    death_year: 397,
    death_place: "Mediolanum, Italia, Roman Empire (modern-day Milan, Italy)",
    canonization_date: "1298-10-04",
    quotes: [
      "No one heals himself by wounding another.",
      "When in Rome, live as the Romans do; when elsewhere, live as they live elsewhere.",
      "No duty is more urgent than that of returning thanks.",
      "It is not the act of a good man to be jealous of anyone; for the good man should rejoice at another's good, as if it were his own.",
      "The Church of the Lord is built upon the rock of the apostles among so many dangers in the world; it therefore remains unmoved. The Church's foundation is unshakable and firm against the assaults of the raging sea.",
      "If it is 'according to the flesh' that Christ has been raised from the dead, it is with a view to our resurrection that he rose.",
      "The devil's snare does not catch you, except you have first caught yourself in the snare of the devil.",
      "Let us take refuge from this world. You can do so in your own mind, if you are willing to do so.",
      "The rich man who gives to the poor does not bestow alms but pays a debt.",
      "Our own evil inclinations are far more dangerous than any external enemies.",
      "Let your door stand open to receive Him, unlock your soul to Him, offer Him a welcome in your mind, and then you will see the riches of simplicity, the treasures of peace, the joy of grace.",
      "The Church of the Lord is built upon the rock of the apostles among so many dangers in the world; it therefore remains unmoved. The Church's foundation is unshakable and firm against the assaults of the raging sea.",
      "It is not the act of a good man to be jealous of anyone; for the good man should rejoice at another's good, as if it were his own.",
      "The devil's snare does not catch you, except you have first caught yourself in the snare of the devil.",
      "The rich man who gives to the poor does not bestow alms but pays a debt."
    ],
    prayers:
      "O God, who made the Bishop Saint Ambrose a teacher of the Catholic faith and a model of apostolic courage, raise up in your Church men after your own heart to govern her with courage and wisdom. Through our Lord Jesus Christ, your Son, who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    books: ["on-the-duties-of-clergy", "on-the-holy-spirit", "on-the-mysteries"],
    is_dominican: false,
    is_doctor: true,
    rank: CelebrationRank.MEMORIAL,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },
  {
    id: "jerome",
    name: "St. Jerome",
    feast_day: "09-30",
    short_bio: "Biblical scholar, translator of the Vulgate, and Doctor of the Church",
    biography: [
      "St. Jerome was born around 347 in Stridon, a town on the border of Dalmatia and Pannonia (in modern-day Croatia). He was sent to Rome for his education, where he studied grammar, rhetoric, and philosophy under the renowned grammarian Aelius Donatus.",
      "Despite receiving an excellent classical education, Jerome was drawn to Christianity. He was baptized around 366 by Pope Liberius. After his studies, he traveled extensively throughout the Roman Empire, spending time in Trier, Aquileia, and Antioch.",
      "In Antioch, Jerome had a profound dream in which he was accused of being a Ciceronian (devoted to classical literature) rather than a Christian. This experience led him to focus more intensely on Christian studies. He withdrew to the desert of Chalcis for four years of hermetic life, where he learned Hebrew from a Jewish convert.",
      "Around 379, Jerome was ordained a priest in Antioch and then went to Constantinople to study Scripture under St. Gregory of Nazianzus. In 382, he returned to Rome, where Pope Damasus I appointed him as his secretary and encouraged him to undertake a new Latin translation of the Bible.",
      "After Pope Damasus died in 384, Jerome left Rome due to criticism and controversy, eventually settling in Bethlehem. There, he established a monastery, continued his biblical translations, and wrote extensively against heresies.",
      "His greatest achievement was the translation of the Bible from the original Hebrew, Aramaic, and Greek into Latin, a version known as the Vulgate, which remained the official Catholic Bible for over a thousand years. He also wrote numerous commentaries on Scripture, historical works, and polemical treatises.",
      "Jerome died on September 30, 420, in Bethlehem. He was declared a Doctor of the Church by Pope Boniface VIII in 1298, along with Ambrose, Augustine, and Gregory the Great.",
    ],
    image_url: "/saints/st-jerome.jpg",
    patronage: "Archaeologists, biblical scholars, librarians, students, translators",
    birth_year: 347,
    birth_place: "Stridon, Dalmatia (modern-day Croatia or Slovenia)",
    death_year: 420,
    death_place: "Bethlehem, Palaestina Prima (modern-day West Bank, Palestine)",
    canonization_date: "1298-10-04",
    quotes: [
      "Ignorance of Scripture is ignorance of Christ.",
      "The Scriptures are shallow enough for a babe to come and drink without fear of drowning and deep enough for a theologian to swim in without ever touching the bottom.",
      "Be ever engaged, so that whenever the devil calls he may find you occupied.",
      "The face is the mirror of the mind, and eyes without speaking confess the secrets of the heart.",
      "The Bible tells us to love our neighbors, and also to love our enemies; generally because they are generally the same people.",
      "Make knowledge of the Scripture your love and you will not love the views of the flesh.",
      "A friend is long sought, hardly found, and with difficulty kept.",
      "The measure of our advancement in the spiritual life should be taken from the progress we make in the virtue of self-denial; for it should be as a schoolmaster to teach us the depth of our own corruption.",
      "Love is not to be purchased, and affection has no price.",
      "The Scriptures are the swaddling clothes of the Lord Jesus, simple in speech, but worthy of the Word of God.",
      "The friendship that can cease has never been real.",
      "The Lord's command to preach the Gospel to all creatures is obligatory on us who are now the salt of the earth and the light of the world.",
      "The measure of our advancement in the spiritual life should be taken from the progress we make in the virtue of self-denial.",
      "The Scriptures are shallow enough for a babe to come and drink without fear of drowning and deep enough for a theologian to swim in without ever touching the bottom.",
      "The face is the mirror of the mind, and eyes without speaking confess the secrets of the heart."
    ],
    prayers:
      "O God, who gave the Priest Saint Jerome a living and tender love for Sacred Scripture, grant that your people may be ever more fruitfully nourished by your Word and find in it the fount of life. Through our Lord Jesus Christ, your Son, who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    books: ["vulgate-bible-translation", "lives-of-illustrious-men", "commentaries-on-scripture"],
    is_dominican: false,
    is_doctor: true,
    rank: CelebrationRank.MEMORIAL,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },
  {
    id: "gregory-the-great",
    name: "St. Gregory the Great",
    feast_day: "09-03",
    short_bio: "Pope, reformer, and one of the four original Doctors of the Church",
    biography: [
      "St. Gregory was born around 540 in Rome to a wealthy patrician family with strong Christian ties. His father was a Roman senator, and his mother, Silvia, is also venerated as a saint. Gregory received an excellent education in law and rhetoric.",
      "After serving as Prefect of Rome at the age of 30, Gregory converted his family home into a monastery dedicated to St. Andrew and became a monk. He founded six more monasteries on his family estates in Sicily.",
      "In 579, Pope Pelagius II ordained him a deacon and sent him as papal ambassador to the imperial court in Constantinople, where he remained for six years. Upon his return to Rome, he became abbot of St. Andrew's Monastery.",
      "When Pope Pelagius died in 590 during a plague epidemic, Gregory was unanimously elected to succeed him, despite his reluctance. As pope, he implemented significant reforms in church administration, liturgy, and missionary work.",
      "Gregory reorganized the Church's vast properties to care for the poor and refugees, reformed the liturgy (the Gregorian chant is named after him), and wrote extensively on pastoral care, morality, and spirituality. His book 'Pastoral Care' became a handbook for bishops for centuries.",
      "He is known for sending St. Augustine of Canterbury and other missionaries to evangelize England in 596. He maintained extensive correspondence with leaders throughout Europe and North Africa, helping to shape the medieval Church.",
      "Despite suffering from poor health throughout much of his pontificate, Gregory worked tirelessly until his death on March 12, 604. He was immediately acclaimed as a saint and was declared one of the four original Doctors of the Church by Pope Boniface VIII in 1298.",
    ],
    image_url: "/saints/st-gregory-the-great.jpg",
    patronage: "Musicians, singers, students, teachers, popes",
    birth_year: 540,
    birth_place: "Rome, Ostrogothic Kingdom (modern-day Italy)",
    death_year: 604,
    death_place: "Rome, Byzantine Empire (modern-day Italy)",
    canonization_date: "1298-10-04",
    quotes: [
      "The proof of love is in the works. Where love exists, it works great things. But when it ceases to act, it ceases to exist.",
      "The Bible is a stream of running water, where alike the elephant may swim, and the lamb walk without losing its feet.",
      "For the place of after pains is on this side of the resurrection, but of eternal torment, beyond it; that the order in the judgment may be the same as in the sin, to wit, that the time of the torment should succeed to the time of the sin.",
      "The only true riches are those that make us rich in virtue. Therefore, if you want to be rich, beloved, love true riches.",
      "The universe is not a machine. God is not an absent watchmaker.",
      "To be silent when we are impugned is an indication of pride. No one wisely abandons the defense of the truth.",
      "The only true riches are those that make us rich in virtue. Therefore, if you want to be rich, beloved, love true riches.",
      "The proof of love is in the works. Where love exists, it works great things. But when it ceases to act, it ceases to exist.",
      "The Bible is a stream of running water, where alike the elephant may swim, and the lamb walk without losing its feet.",
      "For the place of after pains is on this side of the resurrection, but of eternal torment, beyond it; that the order in the judgment may be the same as in the sin, to wit, that the time of the torment should succeed to the time of the sin.",
      "The only true riches are those that make us rich in virtue. Therefore, if you want to be rich, beloved, love true riches.",
      "The universe is not a machine. God is not an absent watchmaker.",
      "To be silent when we are impugned is an indication of pride. No one wisely abandons the defense of the truth.",
      "The only true riches are those that make us rich in virtue. Therefore, if you want to be rich, beloved, love true riches.",
      "The proof of love is in the works. Where love exists, it works great things. But when it ceases to act, it ceases to exist."
    ],
    prayers:
      "O God, who care for your people with gentleness and rule them in love, through the intercession of Pope Saint Gregory, endow, we pray, with a spirit of wisdom those to whom you have given authority to govern, that the flourishing of a holy flock may become the eternal joy of the shepherds. Through our Lord Jesus Christ, your Son, who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    books: ["pastoral-care", "moralia-in-job", "dialogues"],
    is_dominican: false,
    is_doctor: true,
    rank: CelebrationRank.MEMORIAL,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },
  {
    id: "athanasius",
    name: "St. Athanasius",
    feast_day: "05-02",
    short_bio: "Bishop of Alexandria and Doctor of the Church, defender of the divinity of Christ",
    biography: [
      "St. Athanasius was born around 296 in Alexandria, Egypt. Little is known about his early life, but he received a good education in grammar, rhetoric, and theology, and was familiar with Greek literature and philosophy.",
      "As a young man, Athanasius became secretary to Alexander, the Bishop of Alexandria. He attended the First Ecumenical Council of Nicaea in 325, where he played a significant role in defending the full divinity of Christ against the Arian heresy, which claimed that Jesus was not fully divine but a created being.",
      "In 328, Athanasius succeeded Alexander as Bishop of Alexandria. His episcopate was marked by constant struggle against Arianism, which had gained political support despite being condemned at Nicaea. Throughout his career, he was exiled five times, spending a total of 17 years in exile.",
      "During his exiles, Athanasius spent time with the desert monks of Egypt, including St. Anthony the Great, whose biography he wrote. He also traveled to Rome, where he influenced Western theology and monasticism.",
      "Athanasius was a prolific writer whose works defended orthodox Trinitarian theology. His most famous works include 'On the Incarnation,' which explains why God became human in Jesus Christ, and 'Life of Anthony,' which popularized monasticism throughout the Christian world.",
      "Despite facing opposition from emperors and rival bishops, Athanasius remained steadfast in his defense of the Nicene Creed. His persistence earned him the title 'Athanasius Contra Mundum' (Athanasius Against the World).",
      "He died on May 2, 373, in Alexandria. In 1568, Pope Pius V proclaimed him a Doctor of the Church, recognizing his crucial role in defending the divinity of Christ and the doctrine of the Trinity.",
    ],
    image_url: "/saints/st-athanasius.jpg",
    patronage: "Theologians, those struggling against heresy",
    birth_year: 296,
    birth_place: "Alexandria, Roman Egypt (modern-day Egypt)",
    death_year: 373,
    death_place: "Alexandria, Roman Egypt (modern-day Egypt)",
    canonization_date: "1568-05-01",
    quotes: [
      "The Son of God became man so that we might become God.",
      "For the Lord touched all parts of creation, and freed and undeceived them all from every deceit.",
      "The Word of God, incorporeal, incorruptible, and immaterial, entered our world. In one sense, indeed, He was not far from it before, for no part of creation was ever without Him.",
      "The holy and inspired Scriptures are fully sufficient for the proclamation of the truth.",
      "The Word perceived that corruption could not be got rid of otherwise than through death; yet He was, and could not die, being immortal and the Son of the Father. For this reason, therefore, He assumed a body capable of death.",
      "For the Lord did not come to make a display. He came to heal and to teach suffering men. For one who wanted to make a display the thing would have been just to appear and dazzle the beholders.",
      "The Word of God, incorporeal, incorruptible, and immaterial, entered our world. In one sense, indeed, He was not far from it before, for no part of creation was ever without Him.",
      "The Son of God became man so that we might become God.",
      "For the Lord touched all parts of creation, and freed and undeceived them all from every deceit.",
      "The Word of God, incorporeal, incorruptible, and immaterial, entered our world. In one sense, indeed, He was not far from it before, for no part of creation was ever without Him.",
      "The holy and inspired Scriptures are fully sufficient for the proclamation of the truth.",
      "The Word perceived that corruption could not be got rid of otherwise than through death; yet He was, and could not die, being immortal and the Son of the Father. For this reason, therefore, He assumed a body capable of death.",
      "For the Lord did not come to make a display. He came to heal and to teach suffering men. For one who wanted to make a display the thing would have been just to appear and dazzle the beholders.",
      "The Word of God, incorporeal, incorruptible, and immaterial, entered our world. In one sense, indeed, He was not far from it before, for no part of creation was ever without Him.",
      "The Son of God became man so that we might become God."
    ],
    prayers:
      "Almighty ever-living God, who raised up the Bishop Saint Athanasius as an outstanding champion of your Son's divinity, mercifully grant that, rejoicing in his teaching and his protection, we may never cease to grow in knowledge and love of you. Through our Lord Jesus Christ, your Son, who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    books: ["on-the-incarnation", "life-of-anthony", "against-the-arians"],
    is_dominican: false,
    is_doctor: true,
    rank: CelebrationRank.MEMORIAL,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },
  {
    id: "basil-the-great",
    name: "St. Basil the Great",
    feast_day: "01-02",
    short_bio: "Bishop of Caesarea, monastic founder, and Doctor of the Church",
    biography: [
      "St. Basil was born around 330 in Caesarea, Cappadocia (modern-day Turkey), into a wealthy and pious family. His grandmother, St. Macrina the Elder, his parents Sts. Basil the Elder and Emmelia, his sister St. Macrina the Younger, and his brothers Sts. Gregory of Nyssa and Peter of Sebaste are all venerated as saints.",
      "Basil received an excellent education in Caesarea, Constantinople, and Athens, where he formed a close friendship with St. Gregory of Nazianzus. After completing his studies, he taught rhetoric in Caesarea but soon felt called to a more spiritual life.",
      "Around 357, he was baptized and traveled to Egypt, Palestine, Syria, and Mesopotamia to study the monastic life. Inspired by what he saw, he returned to Pontus and established a monastic community on his family estate, where he was joined by friends, including Gregory of Nazianzus.",
      "Basil wrote a rule for monastic life that emphasized community living, liturgical prayer, and manual labor, in contrast to the solitary asceticism common in Egypt. His 'Longer Rules' and 'Shorter Rules' became the foundation for monasticism in the Eastern Church.",
      "In 370, Basil was chosen as Bishop of Caesarea. As bishop, he defended orthodox Trinitarian theology against Arianism, reformed the clergy, established hospitals and homes for the poor, and organized famine relief. His 'Basiliad' was a large complex that cared for the sick, elderly, and travelers.",
      "Basil was a prolific writer whose works include theological treatises, homilies, and letters. His most important theological work, 'On the Holy Spirit,' defends the divinity of the Holy Spirit. He also revised the liturgy of his local church, and the Divine Liturgy of St. Basil is still used in the Eastern Orthodox and Eastern Catholic Churches.",
      "He died on January 1, 379, in Caesarea. In 1568, Pope Pius V proclaimed him a Doctor of the Church, along with Sts. Athanasius, Ambrose, and John Chrysostom, as one of the 'Four Great Doctors of the Eastern Church.'",
    ],
    image_url: "/saints/st-basil-the-great.jpg",
    patronage: "Monks, hospital administrators, reformers, Russia, exorcists",
    birth_year: 330,
    birth_place: "Caesarea, Cappadocia (modern-day Kayseri, Turkey)",
    death_year: 379,
    death_place: "Caesarea, Cappadocia (modern-day Kayseri, Turkey)",
    canonization_date: "1568-09-14",
    quotes: [
      "A tree is known by its fruit; a man by his deeds. A good deed is never lost; he who sows courtesy reaps friendship, and he who plants kindness gathers love.",
      "The bread which you do not use is the bread of the hungry; the garment hanging in your wardrobe is the garment of him who is naked; the shoes that you do not wear are the shoes of the one who is barefoot; the money that you keep locked away is the money of the poor; the acts of charity that you do not perform are so many injustices that you commit.",
      "What is the mark of love for your neighbor? Not to avoid being generous, as some people interpret the word 'neighbor,' but to make sure that you are generous and to prove your love for the poor by your own actions.",
      "The love of God is the highest good, the final blessing, the goal of all desires, the fulfillment of all commandments, the life of all the virtues.",
    ],
    prayers:
      "O God, who were pleased to give light to your Church by the example and teaching of the Bishops Saint Basil the Great and Saint Gregory Nazianzen, grant, we pray, that in humility we may learn your truth and practice it faithfully in charity. Through our Lord Jesus Christ, your Son, who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    books: ["on-the-holy-spirit", "against-eunomius", "monastic-rules"],
    is_dominican: false,
    is_doctor: true,
    rank: CelebrationRank.MEMORIAL,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },

]
