import type { Saint } from "../saint-types"
import { LiturgicalColor } from "../../liturgical-types"
import { CelebrationRank } from "../../celebrations/celebrations-types"

// Medieval Doctors of the Church (7th-15th centuries)
export const medievalDoctors: Saint[] = [
  // Add medieval doctors here - this would include figures like:
  // St. Thomas Aquinas, St. Bonaventure, St. Anselm, etc.
  // For now, keeping this array empty as the original file structure
  // needs to be analyzed to properly categorize existing doctors
  {
    id: "thomas-aquinas",
    name: "St. Thomas Aquinas",
    feast_day: "01-28",
    short_bio: "Doctor of the Church and Dominican theologian",
    biography: [
      "St. Thomas Aquinas was born around 1225 in Roccasecca, Italy, to a noble family. At the age of five, he was sent to the Benedictine monastery at Monte Cassino for education.",
      "Against his family's wishes, Thomas joined the newly founded Dominican Order in 1244. His family went so far as to kidnap him and hold him captive for a year to dissuade him, but he remained steadfast in his vocation.",
      "Thomas studied under St. Albert the Great in Paris and Cologne, where his intellectual brilliance became evident. Despite his profound intellect, he was known for his humility, which earned him the nickname 'the Dumb Ox' from his fellow students.",
      "He taught at the University of Paris and other Italian universities, producing numerous theological and philosophical works. His most famous work, the Summa Theologica, represents the pinnacle of scholastic philosophy and theology.",
      "On December 6, 1273, Thomas had a mystical experience during Mass that led him to stop writing. When urged to continue, he replied, 'I cannot, for all that I have written seems like straw to me compared to what I have seen.'",
      "Thomas died on March 7, 1274, while traveling to the Council of Lyon. He was canonized in 1323 and declared a Doctor of the Church in 1567. Pope Leo XIII declared him the patron of Catholic universities, colleges, and schools in 1880.",
    ],
    image_url: "/saints/st-thomas-aquinas.jpg",
    patronage: "Catholic schools, colleges, universities, students, booksellers, theologians, philosophers",
    birth_year: 1225,
    birth_place: "Roccasecca, Kingdom of Sicily (modern-day Italy)",
    death_year: 1274,
    death_place: "Fossanova Abbey, Papal States (modern-day Italy)",
    canonization_date: "1323-07-18",
    quotes: [
      "To one who has faith, no explanation is necessary. To one without faith, no explanation is possible.",
      "Beware the man of a single book.",
      "The things that we love tell us what we are.",
      "The soul is like an uninhabited world that comes to life only when God lays His head against us.",
      "There is nothing on this earth more to be prized than true friendship.",
      "The study of philosophy is not that we may know what men have thought, but what the truth of things is.",
      "The Eucharist is the sacrament of love: it signifies love, it produces love. The Eucharist is the consummation of the whole spiritual life.",
      "Faith has to do with things that are not seen and hope with things that are not at hand.",
      "The greatest kindness one can render to any man consists in leading him from error to truth.",
      "The truth of our faith becomes a matter of ridicule among the infidels if any Catholic, not gifted with the necessary scientific learning, presents as dogma what scientific scrutiny shows to be false.",
      "Three things are necessary for the salvation of man: to know what he ought to believe; to know what he ought to desire; and to know what he ought to do.",
      "The celebration of Holy Mass is as valuable as the death of Jesus on the cross.",
      "The knowledge of God is the cause of things. For the knowledge of God is to all creatures what the knowledge of the artificer is to things made by his art."
    ],
    prayers:
      "Grant me, O Lord my God, a mind to know you, a heart to seek you, wisdom to find you, conduct pleasing to you, faithful perseverance in waiting for you, and a hope of finally embracing you. Amen.",
    books: [
      "summa-theologica",
      "summa-contra-gentiles",
      "on-being-and-essence",
      "disputed-questions-truth",
      "compendium-theology",
      "commentary-aristotle-ethics",
      "on-power-of-god",
      "commentary-on-sentences",
    ],
    is_dominican: true,
    is_doctor: true,
    rank: CelebrationRank.FEAST,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },
  {
    id: "albert-the-great",
    name: "St. Albert the Great",
    feast_day: "11-15",
    short_bio: "Doctor of the Church, teacher of St. Thomas Aquinas",
    biography: [
      "St. Albert the Great was born around 1200 in Lauingen, Bavaria, Germany. He studied at the University of Padua and later joined the Dominican Order in 1223.",
      "Albert taught at several German convents before becoming a professor at the University of Paris, where he was the first to comment on virtually all of Aristotle's works, making them accessible to wider academic debate.",
      "His vast knowledge earned him the nickname 'Doctor Universalis' (Universal Doctor). He was a pioneer in the study of natural sciences and made significant contributions to the fields of botany, biology, physics, and astronomy.",
      "In 1248, he was sent to Cologne to establish a studium generale, where St. Thomas Aquinas became his student and assistant. Albert recognized Thomas's genius and defended him against critics.",
      "Albert served as the provincial of the Dominican Order's German province and briefly as the Bishop of Regensburg before resigning to return to teaching and writing.",
      "He died on November 15, 1280, in Cologne. Pope Pius XI canonized him in 1931 and declared him a Doctor of the Church. In 1941, Pope Pius XII named him the patron saint of natural scientists.",
    ],
    image_url: "/saints/st-albert-the-great.jpg",
    patronage: "Scientists, philosophers, medical technicians, natural sciences",
    birth_year: 1200,
    birth_place: "Lauingen, Duchy of Bavaria, Holy Roman Empire (modern-day Germany)",
    death_year: 1280,
    death_place: "Cologne, Holy Roman Empire (modern-day Germany)",
    canonization_date: "1931-12-16",
    quotes: [
      "The greater and more persistent your confidence in God, the more abundantly you will receive all that you ask.",
      "The aim of natural science is not simply to accept the statements of others, but to investigate the causes that are at work in nature.",
      "The whole world is theology for us, because the heavens proclaim the glory of God.",
      "Do this in remembrance of me. This is the word of the testament, by which Christ conveyed to the faithful all that He had on earth, and all that He had in heaven.",
      "The most beautiful thing we can experience is the mysterious. It is the source of all true art and science.",
      "It is by the path of love, which is charity, that God draws near to man, and man to God.",
      "The greatest thing a human soul ever does in this world is to see something, and tell what it saw in a plain way.",
      "The test of all knowledge is experiment. Experiment is the sole judge of scientific truth.",
      "In studying nature we have not to inquire how God the Creator may, as He freely wills, use His creatures to work miracles and thereby show forth His power; we have rather to inquire what Nature with its immanent causes can naturally bring to pass.",
      "The teacher must have the soul of an apostle, the zeal of a prophet, the exactitude of a scholar, and the holiness of a saint.",
      "The more we are united to our neighbor, the more we are united to God.",
      "The greatest thing a human soul ever does in this world is to see something, and tell what it saw in a plain way.",
      "The whole world is theology for us, because the heavens proclaim the glory of God."
    ],
    prayers:
      "O God, who made Saint Albert great by his joining of human wisdom to divine faith, grant, we pray, that we may so adhere to the truths he taught, that through progress in learning we may come to a deeper knowledge and love of you. Through our Lord Jesus Christ, your Son, who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    books: ["on-minerals", "commentary-on-dionysius-mystical-theology", "on-animals"],
    is_dominican: true,
    is_doctor: true,
    rank: CelebrationRank.MEMORIAL,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },
  {
    id: "catherine-of-siena",
    name: "St. Catherine of Siena",
    feast_day: "04-29",
    short_bio: "Doctor of the Church and Dominican tertiary",
    biography: [
      "St. Catherine of Siena was born in 1347 in Siena, Italy, the 25th child of Jacopo and Lapa Benincasa. From an early age, she demonstrated exceptional piety and at the age of seven, consecrated her virginity to Christ.",
      "Despite her parents' opposition, Catherine refused to marry and instead joined the Third Order of St. Dominic as a tertiary, living at home in prayer and penance. She received the Dominican habit around the age of 16.",
      "Catherine experienced mystical visions throughout her life, including a spiritual marriage to Christ. In 1368, she underwent what she described as a 'mystical death' followed by a new intimacy with God.",
      "Though she had no formal education, Catherine became influential in both religious and political affairs. She worked tirelessly to bring peace to the warring Italian city-states and to reform the clergy. Her letters to Pope Gregory XI were instrumental in his decision to return the papacy from Avignon to Rome in 1377.",
      "During the Western Schism, Catherine supported the Roman Pope Urban VI and worked for the unity of the Church until her death in 1380 at the age of 33. She was canonized in 1461 by Pope Pius II and declared a Doctor of the Church by Pope Paul VI in 1970, one of only four women to receive this honor.",
    ],
    image_url: "/saints/st-catherine-of-siena.jpg",
    patronage: "Italy, fire prevention, nurses, the sick, miscarriages, sexual temptation",
    birth_year: 1347,
    birth_place: "Siena, Italy",
    death_year: 1380,
    death_place: "Rome, Papal States",
    canonization_date: "June 29, 1461",
    quotes: [
      "Be who God meant you to be and you will set the world on fire.",
      "Nothing great is ever achieved without much enduring.",
      "If you are what you should be, you will set the whole world ablaze!",
      "To the servant of God... every place is the right place, and every time is the right time.",
      "All the way to heaven is heaven, because Jesus said, 'I am the way.'",
      "Start being brave about everything. Drive out darkness and spread light. Don't look at your weaknesses. Realize instead that in Christ crucified you can do everything.",
      "You are rewarded not according to your work or your time but according to the measure of your love.",
      "We are of such value to God that He came to live among us... and to guide us home. He will go to any length to seek us, even to being lifted high upon the cross to draw us back to Himself.",
      "Proclaim the truth and do not be silent through fear.",
      "The soul cannot live without love. She always wants to love something because love is the stuff she is made of, and through love I created her.",
      "There is no perfect obedience without love, and there is no perfect love without obedience.",
      "Eternal God, eternal Trinity... You, a mystery as deep as the sea; the more I search, the more I find, and the more I find the more I search for You.",
      "We've had enough of exhortations to be silent! Cry out with a thousand tongues - I see the world is rotten because of silence!"
    ],
    prayers:
      "O God, who set Saint Catherine of Siena on fire with divine love in her contemplation of the Lord's Passion and her service of your Church, grant, through her intercession, that your people, participating in the mystery of Christ, may ever exult in the revelation of his glory. Who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    books: ["dialogue-catherine-siena", "letters-of-catherine", "prayers-and-revelations"],
    is_dominican: true,
    is_doctor: true,
    rank: CelebrationRank.FEAST,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },
  {
    id: "bonaventure",
    name: "St. Bonaventure",
    feast_day: "07-15",
    short_bio: "Franciscan theologian, Cardinal, and Doctor of the Church",
    biography: [
      "St. Bonaventure was born Giovanni di Fidanza around 1217 in Bagnoregio, Tuscany, Italy. According to tradition, he was cured of a serious childhood illness through the prayers of St. Francis of Assisi, which inspired his name 'Bonaventure' (meaning 'good fortune').",
      "He joined the Franciscan Order around 1243 and studied at the University of Paris, where he later taught alongside St. Thomas Aquinas. Both were students of the great scholar Alexander of Hales. Bonaventure received his doctorate in theology in 1257.",
      "That same year, he was elected Minister General of the Franciscan Order at the age of 40. He led the Franciscans for 17 years during a difficult period, working to preserve unity within the order amid tensions between those who favored a strict interpretation of St. Francis's ideal of poverty and those who favored a more moderate approach.",
      "Bonaventure was a prolific writer whose works combined the intellectual precision of scholasticism with the spiritual depth of mysticism. His major works include 'The Journey of the Mind to God,' 'The Tree of Life,' and 'The Life of St. Francis.' He is often called the 'Seraphic Doctor' because of his burning love for God and his spiritual insights.",
      "In 1273, Pope Gregory X appointed him Cardinal-Bishop of Albano. Bonaventure played a key role in the Second Council of Lyon in 1274, working to reunite the Eastern and Western Churches. However, he died suddenly during the Council on July 15, 1274, possibly from poisoning.",
      "He was canonized in 1482 by Pope Sixtus IV and declared a Doctor of the Church by Pope Sixtus V in 1588. Pope Sixtus V ranked him among the greatest Doctors of the Church, calling him the 'Prince of Mystics.'",
    ],
    image_url: "/saints/st-bonaventure.jpg",
    patronage: "Bowel disorders, Franciscan Studies, theologians",
    birth_year: 1217,
    birth_place: "Bagnoregio, Papal States (modern-day Italy)",
    death_year: 1274,
    death_place: "Lyon, Kingdom of Arles (modern-day France)",
    canonization_date: "1482-04-14",
    quotes: [
      "When we pray, the voice of the heart must be heard more than that proceeding from the mouth.",
      "If you would suffer with patience the adversities and miseries of this life, be a man of prayer. If you would gain power and strength to overcome the temptations of the enemy, be a man of prayer.",
      "The outcome or the fruit of reading Holy Scripture is by no means negligible: it is the fullness of eternal happiness.",
      "The Holy Spirit comes where He is desired, and He is desired where He is not prevented from entering.",
      "Since happiness is nothing else than the enjoyment of the Supreme Good, and the Supreme Good is above us, no one can enjoy happiness unless he rises above himself.",
      "The perfection of a religious man is to do common things in a perfect manner.",
      "The Holy Spirit works in us in two ways: first, by enlightening our understanding to know the truth; second, by inflaming our will with divine love.",
      "The more a man considers that he is nothing, the more God will enter into him with His grace.",
      "Christ is both the way and the door. Christ is the staircase and the vehicle, like the throne of mercy over the Ark of the Covenant, and the mystery hidden from the ages.",
      "In all your deeds and words you should look upon this Jesus as your model. Do so whether you are walking or keeping silence, or speaking, whether you are alone or with others.",
      "The universe is like a book in which the invisible God is made known to us, just as a man is known through the works he has written.",
      "The grace of the Holy Spirit takes away what is evil, gives what is good, and keeps what is given.",
      "When God bestows spiritual graces, His Majesty is bound by no laws.",
      "The more the soul loves, the more it desires, and the more it desires, the more it will find and enjoy God.",
      "Christ is the book of life, and it is written within and without: within by divinity, without by humanity."
    ],
    prayers:
      "Grant, we pray, almighty God, that, just as we celebrate the heavenly birthday of the Bishop Saint Bonaventure, we may benefit from his great learning and constantly imitate the ardor of his charity. Through our Lord Jesus Christ, your Son, who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    books: ["journey-of-mind-to-god", "tree-of-life", "life-of-st-francis"],
    is_dominican: false,
    is_doctor: true,
    rank: CelebrationRank.MEMORIAL,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },

  {
    id: "isidore-of-seville",
    name: "St. Isidore of Seville",
    feast_day: "04-04",
    short_bio: "Archbishop of Seville, scholar, and Doctor of the Church",
    biography: [
      "St. Isidore was born around 560 in Cartagena, Spain, to a family of distinguished lineage. After the death of his parents, he was raised and educated by his older brother, St. Leander, who was the Archbishop of Seville.",
      "Under Leander's guidance, Isidore received an excellent education in Latin, Greek, Hebrew, and various sciences. He became well-versed in classical literature, law, medicine, and theology. His love of learning and books was extraordinary.",
      "Around 600, Isidore succeeded his brother as Archbishop of Seville. As archbishop, he continued the work of converting the Visigothic rulers from Arianism to orthodox Christianity, a process begun by Leander. He also worked to unify the liturgical practices of the Spanish Church.",
      "Isidore presided over several important councils, including the Fourth Council of Toledo in 633, which established uniform liturgical practices throughout Spain and enacted measures for the education of clergy. He also founded schools and promoted education throughout his diocese.",
      "He is best known for his encyclopedic work, 'Etymologies' (or 'Origins'), which attempted to compile all knowledge of his time. This work became one of the most used textbooks of the Middle Ages and preserved much classical learning that might otherwise have been lost.",
      "Besides 'Etymologies,' Isidore wrote numerous other works on theology, history, grammar, natural science, and cosmology. His writings show his concern for education and his desire to preserve and transmit knowledge.",
      "Isidore died on April 4, 636, in Seville. He was canonized by Pope Clement VIII in 1598 and declared a Doctor of the Church by Pope Innocent XIII in 1722. In 1999, Pope John Paul II named him the patron saint of the internet, computers, and computer users because of his efforts to catalog knowledge.",
    ],
    image_url: "/saints/st-isidore-of-seville.jpg",
    patronage: "Internet, computers, computer users, students, schoolchildren",
    birth_year: 560,
    death_year: 636,
    prayers:
      "Hear our prayers, O God, and grant that your Church, instructed by the teaching of Saint Isidore, Bishop and Doctor, may preserve in her heart the things she has received from heaven and express them in deeds of constant love. Through our Lord Jesus Christ, your Son, who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    books: ["etymologies", "on-church-offices", "history-of-the-goths"],
    is_dominican: false,
    is_doctor: true,
    rank: CelebrationRank.MEMORIAL,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },
  {
    id: "bede-the-venerable",
    name: "St. Bede the Venerable",
    feast_day: "05-25",
    short_bio: "Monk, scholar, historian, and Doctor of the Church",
    biography: [
      "St. Bede was born in 672 or 673 in Northumbria, England. At the age of seven, he was entrusted to the care of Benedict Biscop, the abbot of the monastery of St. Peter at Wearmouth. Later, he moved to the monastery's new foundation at Jarrow, where he spent the rest of his life.",
      "Bede was ordained a deacon at the unusually early age of 19 and a priest at 30. He devoted himself to the study of Scripture and to teaching and writing. He learned Latin, Greek, and Hebrew and had access to a fine library brought from Rome by Benedict Biscop.",
      "Despite never traveling beyond Northumbria, Bede became one of the most learned men of his time. He wrote about 40 books, covering history, chronology, lives of saints, commentaries on Scripture, treatises on grammar and natural phenomena, hymns, and poems.",
      "His most famous work is the 'Ecclesiastical History of the English People,' completed in 731, which is the primary source for understanding the conversion of the Anglo-Saxons to Christianity. In this work, Bede introduced the practice of dating events from the birth of Christ (AD/Anno Domini), which eventually became the standard system of dating in the Western world.",
      "Bede was known for his holiness of life, his diligence in study, and his clarity of thought. He was also a skilled teacher and had many students. His approach to scholarship, which emphasized the careful examination of sources and the reconciliation of apparent contradictions, was ahead of his time.",
      "He died on May 25, 735, at Jarrow, after dictating the final passage of his translation of the Gospel of John into Old English. His remains were later transferred to Durham Cathedral.",
      "Bede was declared a Doctor of the Church by Pope Leo XIII in 1899, the only native of Great Britain to receive this honor. He is often called 'The Venerable Bede,' a title that was already attached to his name by the 9th century, reflecting the high esteem in which he was held.",
    ],
    image_url: "/saints/st-bede-the-venerable.jpg",
    patronage: "Historians, scholars, English writers, lectors",
    birth_year: 673,
    death_year: 735,
    prayers:
      "O God, who bring light to your Church through the learning of the Priest Saint Bede, mercifully grant that your servants may always be enlightened by his wisdom and helped by his merits. Through our Lord Jesus Christ, your Son, who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    books: ["ecclesiastical-history", "lives-of-the-abbots", "commentary-on-acts"],
    is_dominican: false,
    is_doctor: true,
    rank: CelebrationRank.MEMORIAL,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },
  {
    id: "peter-damian",
    name: "St. Peter Damian",
    feast_day: "02-21",
    short_bio: "Cardinal, monk, reformer, and Doctor of the Church",
    biography: [
      "St. Peter Damian was born in 1007 in Ravenna, Italy, to a poor family. Orphaned at a young age, he was initially raised by an older brother who mistreated him. Later, another brother, a priest named Damian, took him in and provided for his education, which is why he took the name 'Damian' in gratitude.",
      "Peter studied at Ravenna, Faenza, and Parma, becoming a renowned teacher of rhetoric. Despite his success, he felt called to a more austere life and joined the hermitage of Fonte Avellana around 1035, where he embraced a life of prayer, fasting, and study.",
      "His intellectual abilities and spiritual depth led to his appointment as prior of Fonte Avellana in 1043. Under his leadership, the community grew, and he established five other hermitages. He also wrote a rule for the community that emphasized solitude, prayer, and self-discipline.",
      "Peter became a leading figure in the reform movement of the 11th century, which sought to address corruption and laxity in the Church. He wrote extensively against simony (the buying and selling of Church offices), clerical marriage, and other abuses.",
      "In 1057, despite his reluctance, Pope Stephen IX made him Cardinal-Bishop of Ostia. In this role, he served as a papal legate on various diplomatic missions and continued to advocate for Church reform. After Stephen's death, he supported the election of Pope Nicholas II and later Pope Alexander II against antipopes.",
      "Peter was a prolific writer whose works include letters, sermons, biographies of saints, and theological treatises. His most famous work, 'The Book of Gomorrah,' denounced sexual immorality among the clergy. He also wrote on spiritual topics, emphasizing the contemplative life and the importance of personal reform.",
      "In 1072, after returning from a papal mission to Ravenna, Peter fell ill and died on February 22 at the monastery of Santa Maria degli Angeli near Faenza. He was declared a Doctor of the Church by Pope Leo XII in 1828, recognizing his contributions to Church reform and spiritual theology.",
    ],
    image_url: "/saints/st-peter-damian.jpg",
    patronage: "Reformers, hermits",
    birth_year: 1007,
    death_year: 1072,
    prayers:
      "Grant us, we pray, almighty God, that we may so follow the teaching and example of the Bishop Saint Peter Damian, that, putting nothing before Christ and always ardent in the service of your Church, we may be led to the joys of eternal light. Through our Lord Jesus Christ, your Son, who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    books: ["book-of-gomorrah", "life-of-romuald", "letters"],
    is_dominican: false,
    is_doctor: true,
    rank: CelebrationRank.MEMORIAL,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },
  {
    id: "anselm",
    name: "St. Anselm of Canterbury",
    feast_day: "04-21",
    short_bio: "Archbishop of Canterbury, theologian, and Doctor of the Church",
    biography: [
      "St. Anselm was born in 1033 in Aosta, in the Kingdom of Burgundy (now part of Italy). His father, Gundulf, was a Lombard nobleman, and his mother, Ermenberga, was a pious woman who instilled in him a deep faith.",
      "As a young man, Anselm had a strained relationship with his father and left home at the age of 23. After three years of wandering through Burgundy and France, he arrived at the Benedictine abbey of Bec in Normandy, attracted by the reputation of its prior, Lanfranc.",
      "In 1060, Anselm entered the monastery at Bec, where he quickly distinguished himself for his intellectual abilities and spiritual depth. He became prior in 1063 when Lanfranc left to become abbot of Caen, and then abbot of Bec in 1078.",
      "Under Anselm's leadership, Bec became a center of learning, and his reputation as a theologian and spiritual director grew. He wrote several important philosophical and theological works during this period, including the 'Monologion,' 'Proslogion,' and 'Why God Became Man.'",
      "In 1093, Anselm was appointed Archbishop of Canterbury by King William II of England, though he initially resisted the appointment. His tenure as archbishop was marked by conflicts with both William II and his successor, Henry I, over the rights and independence of the Church.",
      "These conflicts led to Anselm's exile twice: from 1097 to 1100 and from 1103 to 1107. During these periods, he traveled to Rome and wrote some of his most important works. The disputes were eventually resolved with compromises on both sides.",
      "Anselm is known for his philosophical and theological contributions, particularly his ontological argument for the existence of God and his work on the atonement. He is often called the 'Father of Scholasticism' for his method of applying reason to illuminate faith.",
      "He died on April 21, 1109, in Canterbury. He was canonized in 1494 by Pope Alexander VI and declared a Doctor of the Church by Pope Clement XI in 1720.",
    ],
    image_url: "/saints/st-anselm.jpg",
    patronage: "Philosophers, theologians, Canterbury",
    birth_year: 1033,
    death_year: 1109,
    prayers:
      "O God, who led the Bishop Saint Anselm to seek out and teach the depths of your wisdom, grant, we pray, that our faith in you may so aid our understanding, that what we believe by your command may give delight to our hearts. Through our Lord Jesus Christ, your Son, who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    books: ["proslogion", "monologion", "why-god-became-man"],
    is_dominican: false,
    is_doctor: true,
    rank: CelebrationRank.OPTIONAL_MEMORIAL,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },
  {
    id: "bernard-of-clairvaux",
    name: "St. Bernard of Clairvaux",
    feast_day: "08-20",
    short_bio: "Abbot, reformer, mystic, and Doctor of the Church",
    biography: [
      "St. Bernard was born in 1090 near Dijon, France, to a noble family. His father was a knight and his mother, Aleth, was a woman of great piety who had a profound influence on his spiritual development.",
      "In 1113, at the age of 23, Bernard entered the monastery of Cîteaux, bringing with him about 30 companions, including his brothers and friends. Cîteaux was the motherhouse of the Cistercian Order, which had been founded in 1098 as a reform of Benedictine monasticism, emphasizing simplicity, manual labor, and strict observance of the Rule of St. Benedict.",
      "Just three years after his entry, Bernard was sent to establish a new monastery at Clairvaux. As abbot of Clairvaux, he led the community with wisdom and holiness, and the monastery flourished under his leadership. During his lifetime, he founded 68 monasteries throughout Europe.",
      "Bernard became one of the most influential figures of his time, involved in Church politics, theological disputes, and the preaching of the Second Crusade. He was a trusted advisor to popes, kings, and bishops, and his intervention was sought in various ecclesiastical and political matters.",
      "Despite his active involvement in worldly affairs, Bernard was fundamentally a contemplative who wrote extensively on spiritual topics. His sermons on the Song of Songs are considered masterpieces of mystical theology, and his devotion to the humanity of Christ and to the Virgin Mary had a lasting impact on Catholic spirituality.",
      "Bernard was also involved in theological controversies, most notably with Peter Abelard, whose rationalistic approach to theology he opposed. He was a strong defender of orthodox doctrine and played a key role in the condemnation of various heresies.",
      "He died on August 20, 1153, at Clairvaux. He was canonized by Pope Alexander III in 1174 and declared a Doctor of the Church by Pope Pius VIII in 1830. In 1953, Pope Pius XII issued an encyclical, 'Doctor Mellifluus,' commemorating the 800th anniversary of his death and highlighting his contributions to Catholic theology and spirituality.",
    ],
    image_url: "/saints/st-bernard-of-clairvaux.jpg",
    patronage: "Cistercians, beekeepers, candlemakers, Gibraltar",
    birth_year: 1090,
    death_year: 1153,
    prayers:
      "O God, who made the Abbot Saint Bernard a man consumed with zeal for your house and a light shining and burning in your Church, grant, through his intercession, that we may be on fire with the same spirit and walk always as children of light. Through our Lord Jesus Christ, your Son, who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    books: ["on-loving-god", "sermons-on-song-of-songs", "on-consideration"],
    is_dominican: false,
    is_doctor: true,
    rank: CelebrationRank.MEMORIAL,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },
  {
    id: "anthony-of-padua",
    name: "St. Anthony of Padua",
    feast_day: "06-13",
    short_bio: "Franciscan friar, preacher, and Doctor of the Church",
    biography: [
      "St. Anthony was born Fernando Martins de Bulhões in 1195 in Lisbon, Portugal, to a wealthy and noble family. At the age of 15, he entered the Augustinian community of Canons Regular at the Abbey of St. Vincent in Lisbon.",
      "After two years, he transferred to the Abbey of Santa Cruz in Coimbra, where he studied theology and Latin. He was ordained a priest around 1219 or 1220. While at Coimbra, he met Franciscan friars who were on their way to Morocco to preach to the Muslims.",
      "When the bodies of five Franciscans who had been martyred in Morocco were brought to Coimbra, Anthony was deeply moved and decided to join the Franciscan Order. He received permission to leave the Augustinians, joined the Franciscans, and took the name Anthony.",
      "Anthony also set out for Morocco to preach, but he became seriously ill and was forced to return. His ship was blown off course and landed in Sicily. From there, he made his way to Assisi, where he attended the Franciscan General Chapter in 1221 and met St. Francis of Assisi.",
      "Anthony's gifts as a preacher were discovered by chance when he was called upon to speak at an ordination ceremony. His eloquence and knowledge of Scripture impressed his superiors, who assigned him to preach against heresy in northern Italy and southern France.",
      "He became known as the 'Hammer of Heretics' for his effective preaching against the Cathars and Albigensians. He was also a renowned teacher of theology, the first in the Franciscan Order, and taught at the universities of Montpellier and Toulouse.",
      "In 1227, Anthony was appointed provincial superior of northern Italy. In 1228, he resigned this position to devote himself to preaching. He settled in Padua, where he preached his last and most famous series of sermons.",
      "Anthony died on June 13, 1231, at the age of 36, in Arcella, near Padua. He was canonized by Pope Gregory IX less than a year after his death, on May 30, 1232, one of the most quickly canonized saints in Church history. He was declared a Doctor of the Church by Pope Pius XII in 1946.",
    ],
    image_url: "/saints/st-anthony-of-padua.jpg",
    patronage: "Lost items, poor people, travelers, elderly, oppressed people, Padua, Portugal, Brazil",
    birth_year: 1195,
    death_year: 1231,
    prayers:
      "Almighty ever-living God, who gave Saint Anthony of Padua to your people as an outstanding preacher and an intercessor in their need, grant that, with his assistance, we may follow a life of Gospel perfection and know the help of your grace in every difficulty. Through our Lord Jesus Christ, your Son, who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    books: ["sermons-for-sundays", "sermons-for-feasts", "moral-concordances"],
    is_dominican: false,
    is_doctor: true,
    rank: CelebrationRank.MEMORIAL,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },
  
  {
    id: "john-damascene",
    name: "St. John of Damascus",
    feast_day: "12-04",
    short_bio: "Priest, monk, theologian, and Doctor of the Church",
    biography: [
      "St. John was born around 675 in Damascus, Syria, to a wealthy Christian family. His father, Sergius Mansur, was a high official in the court of the Muslim caliph. John received an excellent education in philosophy, theology, and music from a Sicilian monk named Cosmas, whom his father had ransomed from slavery.",
      "John succeeded his father in his position at the court and served as a high official under the caliph. However, when Emperor Leo III the Isaurian began his campaign against sacred images (iconoclasm) around 726, John used his position to defend the veneration of icons, writing several treatises on the subject.",
      "According to tradition, Leo, unable to punish John directly because he lived under Muslim rule, forged a letter in which John appeared to be offering to betray Damascus to the Byzantines. The caliph, believing the forgery, had John's right hand cut off. John prayed before an icon of the Virgin Mary, and his hand was miraculously restored.",
      "After this event, John resigned his position and distributed his wealth to the poor. He entered the monastery of St. Sabas near Jerusalem, where he was ordained a priest and spent the rest of his life in prayer, writing, and theological study.",
      "John's most important work is 'The Fountain of Knowledge,' which includes 'The Dialectic' (on logic), 'On Heresies' (a history of heresies), and 'An Exact Exposition of the Orthodox Faith' (a systematic presentation of Christian doctrine). This last part became a standard textbook of Eastern Orthodox theology.",
      "He also wrote hymns and liturgical poetry that are still used in Eastern Christian liturgies. His defense of icons, based on the Incarnation of Christ, was influential at the Second Council of Nicaea (787), which definitively affirmed the legitimacy of venerating sacred images.",
      "John died around 749 at the monastery of St. Sabas. He was declared a Doctor of the Church by Pope Leo XIII in 1890, recognizing his significant contributions to theology, particularly his defense of sacred images and his systematic presentation of Christian doctrine.",
    ],
    image_url: "/saints/st-john-damascene.jpg",
    patronage: "Pharmacists, icon painters, theology students",
    birth_year: 675,
    death_year: 749,
    prayers:
      "Grant, we pray, O Lord, that we may be helped by the prayers of the Priest Saint John Damascene, so that the true faith, which he excelled in teaching, may always be our light and our strength. Through our Lord Jesus Christ, your Son, who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    books: ["fountain-of-knowledge", "on-holy-images", "sacred-parallels"],
    is_dominican: false,
    is_doctor: true,
    rank: CelebrationRank.MEMORIAL,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },
  {
    id: "hildegard-of-bingen",
    name: "St. Hildegard of Bingen",
    feast_day: "09-17",
    short_bio: "Benedictine abbess, mystic, composer, and Doctor of the Church",
    biography: [
      "St. Hildegard was born in 1098 in Bermersheim, near Alzey, in the Holy Roman Empire (modern-day Germany), the tenth child of a noble family. From an early age, she experienced mystical visions, though she kept them private for many years.",
      "At the age of eight, she was entrusted to the care of Jutta, an anchoress (religious recluse) at the Benedictine monastery in Disibodenberg. Hildegard was educated by Jutta and eventually joined the Benedictine order, making her religious profession around 1115.",
      "When Jutta died in 1136, Hildegard was elected magistra (leader) of the small women's community. As her reputation for wisdom and holiness grew, so did the number of women joining the community. In 1147, she founded a new monastery at Rupertsberg, near Bingen, where she served as abbess.",
      "Around 1150, Hildegard began to record her visions with the encouragement of her spiritual advisor, the monk Volmar, and the approval of Pope Eugenius III. Her first major work, 'Scivias' (Know the Ways of the Lord), describes 26 visions dealing with the relationship between God and humanity, the Church, and the redemption.",
      "Hildegard was extraordinarily multitalented. Besides her theological writings, she composed music, wrote plays, created an alternative alphabet, developed her own language, and wrote works on natural history and medicine. Her musical compositions, including the 'Ordo Virtutum' (Play of the Virtues), are still performed today.",
      "She was also a correspondent with popes, emperors, kings, and other notable figures of her time. She undertook four preaching tours throughout the German lands, which was highly unusual for a woman in the 12th century. She was not afraid to criticize clergy and secular rulers for their failings.",
      "Hildegard died on September 17, 1179, at her abbey in Rupertsberg. Though venerated as a saint locally, she was never formally canonized until 2012, when Pope Benedict XVI extended her liturgical cult to the universal Church. In the same year, he declared her a Doctor of the Church, recognizing her significant contributions to theology, music, medicine, and natural science.",
    ],
    image_url: "/saints/st-hildegard-of-bingen.jpg",
    patronage: "Musicians, writers, linguists, natural scientists, Germany",
    birth_year: 1098,
    death_year: 1179,
    prayers:
      "O God, by whose grace your servant Hildegard, kindled with the Fire of your love, became a burning and shining light in your Church: Grant that we also may be aflame with the spirit of love and discipline, and walk before you as children of light; through Jesus Christ our Lord, who lives and reigns with you, in the unity of the Holy Spirit, one God, now and for ever. Amen.",
    books: ["scivias", "liber-vitae-meritorum", "liber-divinorum-operum"],
    is_dominican: false,
    is_doctor: true,
    rank: CelebrationRank.MEMORIAL,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },
  {
    id: "gregory-of-narek",
    name: "St. Gregory of Narek",
    feast_day: "02-27",
    short_bio: "Armenian monk, poet, mystical theologian, and Doctor of the Church",
    biography: [
      "St. Gregory was born around 951 in the village of Andzevatsik in the historical Armenian region of Vaspurakan (now part of eastern Turkey). He was the son of Khosrov Andzevatsi, a theologian who served as archbishop of the region.",
      "After his mother's death, Gregory and his brother were educated by their maternal cousin, Anania of Narek, who was the founder and abbot of the monastery of Narek on the shores of Lake Van. Gregory eventually joined the monastery as a monk and was ordained a priest.",
      "Gregory spent most of his life at the monastery of Narek, where he gained a reputation as a teacher, poet, and theologian. He lived during a time of significant religious tension in Armenia, with pressure from both Byzantine Orthodox Christians and Muslims.",
      "His masterpiece is the 'Book of Lamentations,' also known as 'Narek,' a collection of 95 mystical prayers or odes in which he expresses his profound sense of human frailty and his longing for God. This work is considered one of the greatest works of Armenian literature and has been translated into many languages.",
      "Gregory also wrote biblical commentaries, panegyrics on the Virgin Mary and the Apostles, and liturgical hymns that are still used in the Armenian Church. His writings are characterized by their rich imagery, emotional depth, and theological insight.",
      "Despite some theological differences between the Armenian Apostolic Church and the Catholic Church, Gregory's works have been appreciated by both traditions for their spiritual depth and theological richness. He is one of the few saints venerated in both the Armenian Apostolic Church and the Catholic Church.",
      "Gregory died around 1003 at the monastery of Narek. He was declared a Doctor of the Church by Pope Francis on April 12, 2015, becoming the first Armenian and the 36th Doctor of the Church. This recognition highlights the ecumenical significance of his work and his contribution to the spiritual heritage of all Christians.",
    ],
    image_url: "/saints/st-gregory-of-narek.jpg",
    patronage: "Armenia, poets, musicians, those suffering from mental illness",
    birth_year: 951,
    death_year: 1003,
    prayers:
      "O God, who bestowed on the Priest Saint Gregory of Narek the grace to express in words of fire your ineffable greatness and your mercy without limit, grant that, through his intercession, we may become living prayers and witnesses of your love in the world. Through our Lord Jesus Christ, your Son, who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    books: ["book-of-lamentations", "commentary-on-song-of-songs", "panegyric-on-the-virgin"],
    is_dominican: false,
    is_doctor: true,
    rank: CelebrationRank.MEMORIAL,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },
]
