import type { Saint } from "../saint-types"
import { LiturgicalColor } from "../../liturgical-types"
import { CelebrationRank } from "../../celebrations/celebrations-types"

// Medieval Doctors of the Church (7th-15th centuries)
export const medievalDoctors: Saint[] = [
  // Add medieval doctors here - this would include figures like:
  // St. Thomas Aquinas, St. Bonaventure, St. Anselm, etc.
  // For now, keeping this array empty as the original file structure
  // needs to be analyzed to properly categorize existing doctors
  {
    id: "thomas-aquinas",
    name: "St. Thomas Aquinas",
    feast_day: "01-28",
    short_bio: "Doctor of the Church and Dominican theologian",
    biography: [
      "St. Thomas Aquinas was born around 1225 in Roccasecca, Italy, to a noble family. At the age of five, he was sent to the Benedictine monastery at Monte Cassino for education.",
      "Against his family's wishes, Thomas joined the newly founded Dominican Order in 1244. His family went so far as to kidnap him and hold him captive for a year to dissuade him, but he remained steadfast in his vocation.",
      "Thomas studied under St. Albert the Great in Paris and Cologne, where his intellectual brilliance became evident. Despite his profound intellect, he was known for his humility, which earned him the nickname 'the Dumb Ox' from his fellow students.",
      "He taught at the University of Paris and other Italian universities, producing numerous theological and philosophical works. His most famous work, the Summa Theologica, represents the pinnacle of scholastic philosophy and theology.",
      "On December 6, 1273, Thomas had a mystical experience during Mass that led him to stop writing. When urged to continue, he replied, 'I cannot, for all that I have written seems like straw to me compared to what I have seen.'",
      "Thomas died on March 7, 1274, while traveling to the Council of Lyon. He was canonized in 1323 and declared a Doctor of the Church in 1567. Pope Leo XIII declared him the patron of Catholic universities, colleges, and schools in 1880.",
    ],
    image_url: "/saints/st-thomas-aquinas.jpg",
    patronage: "Catholic schools, colleges, universities, students, booksellers, theologians, philosophers",
    birth_year: 1225,
    birth_place: "Roccasecca, Kingdom of Sicily (modern-day Italy)",
    death_year: 1274,
    death_place: "Fossanova Abbey, Papal States (modern-day Italy)",
    canonization_date: "1323-07-18",
    quotes: [
      "To one who has faith, no explanation is necessary. To one without faith, no explanation is possible.",
      "Beware the man of a single book.",
      "The things that we love tell us what we are.",
      "The soul is like an uninhabited world that comes to life only when God lays His head against us.",
      "There is nothing on this earth more to be prized than true friendship.",
      "The study of philosophy is not that we may know what men have thought, but what the truth of things is.",
      "The Eucharist is the sacrament of love: it signifies love, it produces love. The Eucharist is the consummation of the whole spiritual life.",
      "Faith has to do with things that are not seen and hope with things that are not at hand.",
      "The greatest kindness one can render to any man consists in leading him from error to truth.",
      "The truth of our faith becomes a matter of ridicule among the infidels if any Catholic, not gifted with the necessary scientific learning, presents as dogma what scientific scrutiny shows to be false.",
      "Three things are necessary for the salvation of man: to know what he ought to believe; to know what he ought to desire; and to know what he ought to do.",
      "The celebration of Holy Mass is as valuable as the death of Jesus on the cross.",
      "The knowledge of God is the cause of things. For the knowledge of God is to all creatures what the knowledge of the artificer is to things made by his art."
    ],
    prayers:
      "Grant me, O Lord my God, a mind to know you, a heart to seek you, wisdom to find you, conduct pleasing to you, faithful perseverance in waiting for you, and a hope of finally embracing you. Amen.",
    books: [
      "summa-theologica",
      "summa-contra-gentiles",
      "on-being-and-essence",
      "disputed-questions-truth",
      "compendium-theology",
      "commentary-aristotle-ethics",
      "on-power-of-god",
      "commentary-on-sentences",
    ],
    is_dominican: true,
    is_doctor: true,
    rank: CelebrationRank.FEAST,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },
  {
    id: "albert-the-great",
    name: "St. Albert the Great",
    feast_day: "11-15",
    short_bio: "Doctor of the Church, teacher of St. Thomas Aquinas",
    biography: [
      "St. Albert the Great was born around 1200 in Lauingen, Bavaria, Germany. He studied at the University of Padua and later joined the Dominican Order in 1223.",
      "Albert taught at several German convents before becoming a professor at the University of Paris, where he was the first to comment on virtually all of Aristotle's works, making them accessible to wider academic debate.",
      "His vast knowledge earned him the nickname 'Doctor Universalis' (Universal Doctor). He was a pioneer in the study of natural sciences and made significant contributions to the fields of botany, biology, physics, and astronomy.",
      "In 1248, he was sent to Cologne to establish a studium generale, where St. Thomas Aquinas became his student and assistant. Albert recognized Thomas's genius and defended him against critics.",
      "Albert served as the provincial of the Dominican Order's German province and briefly as the Bishop of Regensburg before resigning to return to teaching and writing.",
      "He died on November 15, 1280, in Cologne. Pope Pius XI canonized him in 1931 and declared him a Doctor of the Church. In 1941, Pope Pius XII named him the patron saint of natural scientists.",
    ],
    image_url: "/saints/st-albert-the-great.jpg",
    patronage: "Scientists, philosophers, medical technicians, natural sciences",
    birth_year: 1200,
    birth_place: "Lauingen, Duchy of Bavaria, Holy Roman Empire (modern-day Germany)",
    death_year: 1280,
    death_place: "Cologne, Holy Roman Empire (modern-day Germany)",
    canonization_date: "1931-12-16",
    quotes: [
      "The greater and more persistent your confidence in God, the more abundantly you will receive all that you ask.",
      "The aim of natural science is not simply to accept the statements of others, but to investigate the causes that are at work in nature.",
      "The whole world is theology for us, because the heavens proclaim the glory of God.",
      "Do this in remembrance of me. This is the word of the testament, by which Christ conveyed to the faithful all that He had on earth, and all that He had in heaven.",
      "The most beautiful thing we can experience is the mysterious. It is the source of all true art and science.",
      "It is by the path of love, which is charity, that God draws near to man, and man to God.",
      "The greatest thing a human soul ever does in this world is to see something, and tell what it saw in a plain way.",
      "The test of all knowledge is experiment. Experiment is the sole judge of scientific truth.",
      "In studying nature we have not to inquire how God the Creator may, as He freely wills, use His creatures to work miracles and thereby show forth His power; we have rather to inquire what Nature with its immanent causes can naturally bring to pass.",
      "The teacher must have the soul of an apostle, the zeal of a prophet, the exactitude of a scholar, and the holiness of a saint.",
      "The more we are united to our neighbor, the more we are united to God.",
      "The greatest thing a human soul ever does in this world is to see something, and tell what it saw in a plain way.",
      "The whole world is theology for us, because the heavens proclaim the glory of God."
    ],
    prayers:
      "O God, who made Saint Albert great by his joining of human wisdom to divine faith, grant, we pray, that we may so adhere to the truths he taught, that through progress in learning we may come to a deeper knowledge and love of you. Through our Lord Jesus Christ, your Son, who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    books: ["on-minerals", "commentary-on-dionysius-mystical-theology", "on-animals"],
    is_dominican: true,
    is_doctor: true,
    rank: CelebrationRank.MEMORIAL,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },
  {
    id: "catherine-of-siena",
    name: "St. Catherine of Siena",
    feast_day: "04-29",
    short_bio: "Doctor of the Church and Dominican tertiary",
    biography: [
      "St. Catherine of Siena was born in 1347 in Siena, Italy, the 25th child of Jacopo and Lapa Benincasa. From an early age, she demonstrated exceptional piety and at the age of seven, consecrated her virginity to Christ.",
      "Despite her parents' opposition, Catherine refused to marry and instead joined the Third Order of St. Dominic as a tertiary, living at home in prayer and penance. She received the Dominican habit around the age of 16.",
      "Catherine experienced mystical visions throughout her life, including a spiritual marriage to Christ. In 1368, she underwent what she described as a 'mystical death' followed by a new intimacy with God.",
      "Though she had no formal education, Catherine became influential in both religious and political affairs. She worked tirelessly to bring peace to the warring Italian city-states and to reform the clergy. Her letters to Pope Gregory XI were instrumental in his decision to return the papacy from Avignon to Rome in 1377.",
      "During the Western Schism, Catherine supported the Roman Pope Urban VI and worked for the unity of the Church until her death in 1380 at the age of 33. She was canonized in 1461 by Pope Pius II and declared a Doctor of the Church by Pope Paul VI in 1970, one of only four women to receive this honor.",
    ],
    image_url: "/saints/st-catherine-of-siena.jpg",
    patronage: "Italy, fire prevention, nurses, the sick, miscarriages, sexual temptation",
    birth_year: 1347,
    birth_place: "Siena, Italy",
    death_year: 1380,
    death_place: "Rome, Papal States",
    canonization_date: "June 29, 1461",
    quotes: [
      "Be who God meant you to be and you will set the world on fire.",
      "Nothing great is ever achieved without much enduring.",
      "If you are what you should be, you will set the whole world ablaze!",
      "To the servant of God... every place is the right place, and every time is the right time.",
      "All the way to heaven is heaven, because Jesus said, 'I am the way.'",
      "Start being brave about everything. Drive out darkness and spread light. Don't look at your weaknesses. Realize instead that in Christ crucified you can do everything.",
      "You are rewarded not according to your work or your time but according to the measure of your love.",
      "We are of such value to God that He came to live among us... and to guide us home. He will go to any length to seek us, even to being lifted high upon the cross to draw us back to Himself.",
      "Proclaim the truth and do not be silent through fear.",
      "The soul cannot live without love. She always wants to love something because love is the stuff she is made of, and through love I created her.",
      "There is no perfect obedience without love, and there is no perfect love without obedience.",
      "Eternal God, eternal Trinity... You, a mystery as deep as the sea; the more I search, the more I find, and the more I find the more I search for You.",
      "We've had enough of exhortations to be silent! Cry out with a thousand tongues - I see the world is rotten because of silence!"
    ],
    prayers:
      "O God, who set Saint Catherine of Siena on fire with divine love in her contemplation of the Lord's Passion and her service of your Church, grant, through her intercession, that your people, participating in the mystery of Christ, may ever exult in the revelation of his glory. Who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    books: ["dialogue-catherine-siena", "letters-of-catherine", "prayers-and-revelations"],
    is_dominican: true,
    is_doctor: true,
    rank: CelebrationRank.FEAST,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },
  {
    id: "bonaventure",
    name: "St. Bonaventure",
    feast_day: "07-15",
    short_bio: "Franciscan theologian, Cardinal, and Doctor of the Church",
    biography: [
      "St. Bonaventure was born Giovanni di Fidanza around 1217 in Bagnoregio, Tuscany, Italy. According to tradition, he was cured of a serious childhood illness through the prayers of St. Francis of Assisi, which inspired his name 'Bonaventure' (meaning 'good fortune').",
      "He joined the Franciscan Order around 1243 and studied at the University of Paris, where he later taught alongside St. Thomas Aquinas. Both were students of the great scholar Alexander of Hales. Bonaventure received his doctorate in theology in 1257.",
      "That same year, he was elected Minister General of the Franciscan Order at the age of 40. He led the Franciscans for 17 years during a difficult period, working to preserve unity within the order amid tensions between those who favored a strict interpretation of St. Francis's ideal of poverty and those who favored a more moderate approach.",
      "Bonaventure was a prolific writer whose works combined the intellectual precision of scholasticism with the spiritual depth of mysticism. His major works include 'The Journey of the Mind to God,' 'The Tree of Life,' and 'The Life of St. Francis.' He is often called the 'Seraphic Doctor' because of his burning love for God and his spiritual insights.",
      "In 1273, Pope Gregory X appointed him Cardinal-Bishop of Albano. Bonaventure played a key role in the Second Council of Lyon in 1274, working to reunite the Eastern and Western Churches. However, he died suddenly during the Council on July 15, 1274, possibly from poisoning.",
      "He was canonized in 1482 by Pope Sixtus IV and declared a Doctor of the Church by Pope Sixtus V in 1588. Pope Sixtus V ranked him among the greatest Doctors of the Church, calling him the 'Prince of Mystics.'",
    ],
    image_url: "/saints/st-bonaventure.jpg",
    patronage: "Bowel disorders, Franciscan Studies, theologians",
    birth_year: 1217,
    birth_place: "Bagnoregio, Papal States (modern-day Italy)",
    death_year: 1274,
    death_place: "Lyon, Kingdom of Arles (modern-day France)",
    canonization_date: "1482-04-14",
    quotes: [
      "When we pray, the voice of the heart must be heard more than that proceeding from the mouth.",
      "If you would suffer with patience the adversities and miseries of this life, be a man of prayer. If you would gain power and strength to overcome the temptations of the enemy, be a man of prayer.",
      "The outcome or the fruit of reading Holy Scripture is by no means negligible: it is the fullness of eternal happiness.",
      "The Holy Spirit comes where He is desired, and He is desired where He is not prevented from entering.",
      "Since happiness is nothing else than the enjoyment of the Supreme Good, and the Supreme Good is above us, no one can enjoy happiness unless he rises above himself.",
      "The perfection of a religious man is to do common things in a perfect manner.",
      "The Holy Spirit works in us in two ways: first, by enlightening our understanding to know the truth; second, by inflaming our will with divine love.",
      "The more a man considers that he is nothing, the more God will enter into him with His grace.",
      "Christ is both the way and the door. Christ is the staircase and the vehicle, like the throne of mercy over the Ark of the Covenant, and the mystery hidden from the ages.",
      "In all your deeds and words you should look upon this Jesus as your model. Do so whether you are walking or keeping silence, or speaking, whether you are alone or with others.",
      "The universe is like a book in which the invisible God is made known to us, just as a man is known through the works he has written.",
      "The grace of the Holy Spirit takes away what is evil, gives what is good, and keeps what is given.",
      "When God bestows spiritual graces, His Majesty is bound by no laws.",
      "The more the soul loves, the more it desires, and the more it desires, the more it will find and enjoy God.",
      "Christ is the book of life, and it is written within and without: within by divinity, without by humanity."
    ],
    prayers:
      "Grant, we pray, almighty God, that, just as we celebrate the heavenly birthday of the Bishop Saint Bonaventure, we may benefit from his great learning and constantly imitate the ardor of his charity. Through our Lord Jesus Christ, your Son, who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    books: ["journey-of-mind-to-god", "tree-of-life", "life-of-st-francis"],
    is_dominican: false,
    is_doctor: true,
    rank: CelebrationRank.MEMORIAL,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },

]
