import type { Saint } from "../saint-types"
import { LiturgicalColor } from "../../liturgical-types"
import { CelebrationRank } from "../../celebrations/celebrations-types"

// Reformation Era Doctors of the Church (16th-17th centuries)
export const reformationDoctors: Saint[] = [
  // Add reformation era doctors here - this would include figures like:
  // St. Teresa of Avila, St. John of the Cross, St. Peter Canisius, etc.
  // For now, keeping this array empty as the original file structure
  // needs to be analyzed to properly categorize existing doctors
  {
    id: "john-of-the-cross",
    name: "St. John of the Cross",
    feast_day: "12-14",
    short_bio: "Spanish mystic, Carmelite friar, and Doctor of the Church",
    biography: [
      "St. John of the Cross was born Juan de Yepes y Álvarez in Fontiveros, Spain, in 1542. His father, who was of noble birth, died when John was young, leaving the family in poverty. John received his early education at a school for poor children in Medina del Campo.",
      "In 1563, he entered the Carmelite Order, taking the name John of St. Matthias. He was ordained a priest in 1567 and considered joining the stricter Carthusian Order until he met St. Teresa of Ávila, who persuaded him to help her reform the Carmelite Order instead.",
      "In 1568, John established the first monastery of the reformed or 'Discalced' (barefoot) Carmelite friars at Duruelo, changing his name to John of the Cross. The reform faced strong opposition from within the Carmelite Order.",
      "In 1577, John was imprisoned by unreformed Carmelites in Toledo for nine months in a tiny cell. During this time of great suffering, he composed some of his greatest poetry, including the beginning of his masterpiece, 'The Spiritual Canticle.'",
      "After escaping from prison, John continued his work of reform and spiritual direction. He wrote several major works of mystical theology, including 'The Dark Night of the Soul,' 'The Ascent of Mount Carmel,' and 'The Living Flame of Love.'",
      "He died on December 14, 1591, in Úbeda, after being mistreated by his provincial superior. He was canonized in 1726 by Pope Benedict XIII and declared a Doctor of the Church by Pope Pius XI in 1926.",
    ],
    image_url: "/saints/st-john-of-the-cross.jpg",
    patronage: "Contemplative life, mystics, Spanish poets",
    birth_year: 1542,
    birth_place: "Fontiveros, Crown of Castile (modern-day Spain)",
    death_year: 1591,
    death_place: "Úbeda, Crown of Castile (modern-day Spain)",
    canonization_date: "1726-12-27",
    quotes: [
      "In the evening of life, we will be judged on love alone.",
      "Where there is no love, put love, and you will find love.",
      "In the inner stillness where meditation leads, the Spirit secretly anoints the soul and heals our deepest wounds.",
      "The soul that is attached to anything, however much good there may be in it, will not arrive at the liberty of divine union.",
      "A soul makes room for God by wiping away all the smudges and smears of creatures, by uniting its will perfectly to God's; for to love is to labor to divest and deprive oneself for God of all that is not God.",
      "The endurance of darkness is the preparation for great light.",
      "God desires the smallest degree of purity of conscience in you more than all the works you can perform.",
      "Live in the world as if only God and your soul were in it; then your heart will never be made captive by any earthly thing.",
      "The soul that walks in love neither tires others nor grows tired.",
      "In tribulation immediately draw near to God with confidence, and you will receive strength, enlightenment, and instruction.",
      "What we need most in order to make progress is to be silent before this great God with our appetite and with our tongue, for the language he best hears is silent love.",
      "If you do not learn to deny yourself, you can make no progress in perfection.",
      "The very pure spirit does not bother about the regard of others or human respect, but communes inwardly with God, alone and in solitude as to all forms, and with delightful tranquility, for the knowledge of God is received in divine silence.",
      "O you souls who wish to go on with so much safety and consolation, if you knew how much you would please the Lord and be useful to yourselves and others by going to God through the way of the cross, you would never take another path.",
      "The soul that is quick to turn to speaking and conversing is slow to turn to God."
    ],
    prayers:
      "O God, who gave the Priest Saint John an outstanding dedication to perfect self-denial and love of the Cross, grant that, by imitating him closely at all times, we may come to contemplate eternally your glory. Through our Lord Jesus Christ, your Son, who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    books: ["dark-night-of-the-soul", "ascent-of-mount-carmel", "spiritual-canticle"],
    is_dominican: false,
    is_doctor: true,
    rank: CelebrationRank.MEMORIAL,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },
  {
    id: "teresa-of-avila",
    name: "St. Teresa of Ávila",
    feast_day: "10-15",
    short_bio: "Spanish mystic, Carmelite nun, and Doctor of the Church",
    biography: [
      "St. Teresa was born Teresa de Cepeda y Ahumada in Ávila, Spain, on March 28, 1515. She was raised in a devout Spanish noble family and was drawn to religious life from an early age.",
      "At the age of 20, she entered the Carmelite Monastery of the Incarnation in Ávila. After struggling with illness and a somewhat lax religious environment, she experienced a profound conversion at the age of 39 while praying before an image of the wounded Christ.",
      "Inspired by this experience, Teresa embarked on a mission to reform the Carmelite Order, returning to the original strict observance of its rule. In 1562, she founded the first reformed Carmelite convent, St. Joseph's in Ávila, despite significant opposition.",
      "Over the next 20 years, Teresa established 17 more reformed convents throughout Spain. She collaborated with St. John of the Cross to extend her reform to the male branch of the Carmelite Order, leading to the establishment of the Discalced (barefoot) Carmelites.",
      "Teresa was a prolific writer, producing works that are now considered classics of mystical literature and practical spiritual guidance. Her major works include 'The Way of Perfection,' 'The Interior Castle,' and her autobiography, 'The Life of Teresa of Jesus.'",
      "She died on October 4, 1582, in Alba de Tormes. She was canonized in 1622 by Pope Gregory XV and declared a Doctor of the Church by Pope Paul VI in 1970, the first woman to receive this honor along with St. Catherine of Siena.",
    ],
    image_url: "/saints/st-teresa-of-avila.jpg",
    patronage: "Spain, religious, headache sufferers, chess, lace makers",
    birth_year: 1515,
    birth_place: "Ávila, Crown of Castile (modern-day Spain)",
    death_year: 1582,
    death_place: "Alba de Tormes, Crown of Castile (modern-day Spain)",
    canonization_date: "1622-03-12",
    quotes: [
      "Let nothing disturb you, let nothing frighten you, all things are passing away: God never changes. Patience obtains all things. Whoever has God lacks nothing; God alone suffices.",
      "Christ has no body now but yours. No hands, no feet on earth but yours. Yours are the eyes through which he looks compassion on this world. Yours are the feet with which he walks to do good. Yours are the hands through which he blesses all the world.",
      "Prayer is nothing else than being on terms of friendship with God.",
      "We can only learn to know ourselves and do what we can - namely, surrender our will and fulfill God's will in us.",
      "There is more value in a little study of humility and in a single act of it than in all the knowledge in the world.",
      "Accustom yourself continually to make many acts of love, for they enkindle and melt the soul.",
      "To have courage for whatever comes in life - everything lies in that.",
      "The important thing is not to think much but to love much; and so do that which best stirs you to love.",
      "We shall never learn to know ourselves except by endeavoring to know God; for, beholding His greatness, we realize our own littleness; His purity shows us our foulness; and by meditating upon His humility we find how very far we are from being humble.",
      "The feeling remains that God is on the journey, too.",
      "God withholds Himself from no one who perseveres.",
      "It is love alone that gives worth to all things.",
      "We need no wings to go in search of Him, but have only to look upon Him present within us.",
      "The devil's snares can never catch us if we are humble and suspicious of our own strength.",
      "There is no such thing as bad weather. All weather is good because it is God's."
    ],
    prayers:
      "Let nothing disturb you, let nothing frighten you. All things pass away: God never changes. Patience obtains all things. Those who have God find they lack nothing; God alone suffices. Amen.",
    books: ["interior-castle", "way-of-perfection", "life-of-teresa"],
    is_dominican: false,
    is_doctor: true,
    rank: CelebrationRank.MEMORIAL,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },
  {
    id: "john-of-avila",
    name: "St. John of Avila",
    feast_day: "05-10",
    short_bio: "Spanish priest, preacher, and Doctor of the Church",
    biography: [
      "St. John of Avila was born on January 6, 1499, in Almodóvar del Campo, Spain, to a wealthy family of Jewish converso descent. He studied law at the University of Salamanca but left after a spiritual conversion to pursue a life dedicated to God.",
      "After studying philosophy and theology at the University of Alcalá, John was ordained a priest around 1525. He celebrated his first Mass in his hometown and gave away his considerable inheritance to the poor.",
      "John planned to become a missionary in Mexico, but the Archbishop of Seville, impressed by his preaching, convinced him to stay and evangelize in Andalusia, Spain. His powerful sermons, deep spirituality, and personal holiness made him one of the most influential figures in the religious reform of 16th-century Spain.",
      "His outspoken preaching against the moral corruption of the wealthy and powerful led to his imprisonment by the Inquisition on suspicion of heretical teachings. After being cleared of all charges, he continued his ministry with even greater zeal.",
      "John became a spiritual director to many saints of the Spanish Counter-Reformation, including St. Teresa of Avila, St. John of God, and St. Francis Borgia. His writings, especially 'Audi, Filia' (Listen, Daughter), had a profound influence on Spanish spirituality.",
      "He founded several colleges and universities to provide proper education for priests, anticipating many of the reforms later adopted by the Council of Trent. He died on May 10, 1569, in Montilla, Spain, after a long illness.",
      "John of Avila was canonized by Pope Paul VI in 1970 and declared a Doctor of the Church by Pope Benedict XVI in 2012, recognizing his profound influence on Christian spirituality and reform.",
    ],
    image_url: "/saints/st-john-of-avila.jpg",
    patronage: "Spanish clergy, spiritual directors, theologians, Andalusia",
    birth_year: 1499,
    birth_place: "Almodóvar del Campo, Crown of Castile (modern-day Spain)",
    death_year: 1569,
    death_place: "Montilla, Crown of Castile (modern-day Spain)",
    canonization_date: "2012-10-07",
    quotes: [
      "One act of thanksgiving made when things go wrong is worth a thousand thanks when things are agreeable to our inclinations.",
      "The soul that is quick to turn to speaking and conversing is slow to turn to God.",
      "The more we empty ourselves of the love of creatures, the more we shall be filled with the love of God.",
      "In the spiritual life, he who does not advance goes backward. He who does not climb the mountain is falling.",
      "The soul that is quick to turn to speaking and conversing is slow to turn to God.",
      "God values in us the perfection of our love rather than the perfection of our works.",
      "The measure of love is to love without measure.",
      "The soul that is attached to anything, however much good there may be in it, will not arrive at the liberty of divine union.",
      "In the evening of life, we will be judged on love alone.",
      "The soul that walks in love neither tires others nor grows tired.",
      "What we need most in order to make progress is to be silent before this great God with our appetite and with our tongue, for the language he best hears is silent love.",
      "The very pure spirit does not bother about the regard of others or human respect, but communes inwardly with God, alone and in solitude as to all forms, and with delightful tranquility, for the knowledge of God is received in divine silence.",
      "O you souls who wish to go on with so much safety and consolation, if you knew how much you would please the Lord and be useful to yourselves and others by going to God through the way of the cross, you would never take another path.",
      "The soul that is quick to turn to speaking and conversing is slow to turn to God."
    ],
    prayers:
      "Almighty and eternal God, who made the Priest Saint John of Avila an outstanding preacher of the Gospel and a guide for souls on the path of salvation, grant that, through his intercession, we may be faithful to the Christian life to which you have called us and so show to the world the joy of being your disciples. Through our Lord Jesus Christ, your Son, who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    books: ["audi-filia", "spiritual-letters", "treatise-on-the-priesthood"],
    is_dominican: false,
    is_doctor: true,
    rank: CelebrationRank.MEMORIAL,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },
  {
    id: "francis-de-sales",
    name: "St. Francis de Sales",
    feast_day: "01-24",
    short_bio: "Bishop of Geneva, Doctor of the Church, and patron of writers",
    biography: [
      "St. Francis de Sales was born on August 21, 1567, in the Château de Sales near Thorens-Glières, Savoy, to a noble family. He received an excellent education, studying at the Jesuit college of Clermont in Paris and later at the University of Padua, where he earned doctorates in law and theology.",
      "Despite his father's plans for him to pursue a career in law and politics, Francis felt called to the priesthood. After a profound spiritual crisis regarding predestination, which was resolved through his devotion to the Blessed Virgin Mary, he was ordained in 1593.",
      "Francis volunteered to evangelize the Chablais region of Switzerland, which had become Calvinist. Over the course of four years (1594-1598), he converted thousands back to Catholicism through his gentle approach, clear teaching, and personal example. He often wrote pamphlets explaining Catholic doctrine, which he would slip under doors when people refused to speak with him.",
      "In 1602, he was appointed Bishop of Geneva, though he resided in Annecy (now part of France) since Geneva remained under Calvinist control. As bishop, he was known for his gentleness, patience, and understanding in dealing with both clergy and laity.",
      "In 1604, while in Dijon giving a series of Lenten sermons, he met the widowed Baroness Jane Frances de Chantal. Their spiritual friendship led to the founding of the Order of the Visitation of Holy Mary in 1610, which accepted women who were rejected by other orders because of age or health.",
      "Francis was a prolific writer whose works on spiritual direction, particularly 'Introduction to the Devout Life' and 'Treatise on the Love of God,' emphasized that holiness is possible for everyone, not just religious or clergy. He is known for his practical approach to spirituality and his emphasis on love rather than fear.",
      "He died on December 28, 1622, in Lyon, France. He was canonized in 1665 by Pope Alexander VII and declared a Doctor of the Church by Pope Pius IX in 1877. In 1923, Pope Pius XI named him the patron saint of writers and journalists.",
    ],
    image_url: "/saints/st-francis-de-sales.jpg",
    patronage: "Writers, journalists, authors, the deaf, educators, teachers",
    birth_year: 1567,
    birth_place: "Château de Sales, Thorens-Glières, Duchy of Savoy (now France)",
    death_year: 1622,
    death_place: "Lyon, France",
    canonization_date: "1665-04-19",
    prayers:
      "Be at peace. Do not look forward in fear to the changes of life; rather look to them with full hope that as they arise, God, whose very own you are, will lead you safely through all things. And when you cannot stand it, God will carry you in His arms. Do not fear what may happen tomorrow; the same everlasting Father who cares for you today will take care of you then and every day. He will either shield you from suffering or will give you unfailing strength to bear it. Be at peace, and put aside all anxious thoughts and imaginations. Amen.",
    books: ["introduction-to-devout-life", "treatise-on-love-of-god", "spiritual-conferences"],
    type: "universal",
    quotes: [
      "Have patience with all things, but chiefly have patience with yourself. Do not lose courage in considering your own imperfections but instantly set about remedying them - every day begin the task anew.",
      "Nothing is so strong as gentleness, nothing so gentle as real strength.",
      "Do not wish to be anything but what you are, and try to be that perfectly.",
      "The same everlasting Father who cares for you today will take care of you tomorrow and every day. Either He will shield you from suffering or He will give you unfailing strength to bear it.",
      "Never be in a hurry; do everything quietly and in a calm spirit. Do not lose your inner peace for anything whatsoever, even if your whole world seems upset.",
      "You learn to speak by speaking, to study by studying, to run by running, to work by working; and just so, you learn to love God and man by loving. All those who think to learn in any other way deceive themselves.",
      "The measure of love is to love without measure.",
      "We must fear God out of love, not love Him out of fear.",
      "The highest degree of meekness consists in seeing, serving, honoring, and treating amiably, on occasion, those who are not to our taste, and who show themselves unfriendly, unkind, or troublesome to us.",
      "All the science of the saints is included in these two things: To do, and to suffer. And whoever had done these two things best, has made himself most saintly.",
      "The virtue of patience is the one which most assures us of perfection.",
      "There is no danger if our prayer is without words or reflection because the good success of prayer depends neither on words nor on study. It depends upon the simple raising of our minds to God, and the more simple and stripped of feeling it is, the surer it is.",
      "We must not be discouraged by our faults, for children fall frequently in the process of learning to walk, and for a long time after they have learned.",
      "The test of a preacher is that his congregation goes away saying, not what a lovely sermon, but, I will do something!"
    ],
    is_dominican: false,
    is_doctor: true,
    rank: CelebrationRank.MEMORIAL,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },

]
