// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rimpzfnxwqmamplowaoq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpbXB6Zm54d3FtYW1wbG93YW9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2OTM0OTMsImV4cCI6MjA2MzI2OTQ5M30.-H1a7-XfKnxXmWh7AyD2rnHI3_1rYaMsr0IS8Ysc1dw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);