import type { Saint } from "./saint-types"
import { LiturgicalColor } from "../liturgical-types"
import { CelebrationRank } from "../celebrations/celebrations-types"

// Doctors of the Church
export const doctorSaints: Saint[] = [
  {
    id: "gregory-nazianzen",
    name: "St. Gregory of Nazianzus",
    feast_day: "01-02",
    short_bio: "Archbishop of Constantinople, theologian, and Doctor of the Church",
    biography: [
      "St. Gregory was born around 329 in Arianzus, near Nazianzus in Cappadocia (modern-day Turkey), to a wealthy and religious family. His father, Gregory the Elder, was the bishop of Nazianzus, and his mother, Nonna, is also venerated as a saint.",
      "Gregory received an excellent education in Caesarea, Alexandria, and Athens, where he formed a deep friendship with St. Basil the Great. After completing his studies, he returned home and was baptized around 358.",
      "Despite his desire for a contemplative life, Gregory was ordained a priest by his father in 361, somewhat against his will. He briefly fled to join Basil in Pontus but returned to assist his aging father. During this time, he wrote many of his theological works and poems.",
      "In 372, Basil, now Bishop of Caesarea, appointed Gregory as Bishop of Sasima, a small, unpleasant town, as part of his strategy against Arianism. Gregory never took up this position but instead continued to help his father in Nazianzus.",
      "After his father's death, Gregory retired to a monastery in Seleucia but was called to Constantinople in 379 to lead the small orthodox community there, which was surrounded by Arians. His brilliant preaching and theological acumen earned him the title 'The Theologian.'",
      "In 381, Gregory presided over the First Council of Constantinople, which completed the Nicene Creed. However, facing opposition from various quarters, he resigned his see and returned to Nazianzus, where he served as bishop until 384 before retiring to his family estate in Arianzus.",
      "Gregory was a prolific writer, composing theological orations, letters, and poems. His most famous works are the 'Five Theological Orations,' which defend the divinity of Christ and the Holy Spirit. He died around 390 in Arianzus and was declared a Doctor of the Church by Pope Pius V in 1568.",
    ],
    image_url: "/saints/st-gregory-nazianzen.jpg",
    patronage: "Poets, theologians, philosophers",
    birth_year: 329,
    birth_place: "Arianzus, Cappadocia (modern-day Turkey)",
    death_year: 390,
    death_place: "Arianzus, Cappadocia (modern-day Turkey)",
    canonization_date: "1568-09-20",
    quotes: [
      "A little sanctity is the greatest of calamities, for it is pride in sheep's clothing.",
      "Remember God more often than you breathe.",
      "For the Trinity of the same Godhead, the Father, the Son, and the Holy Ghost, is one and the same God, not three Gods, but one God in three Persons.",
      "The Word of God is the true light that enlightens every man coming into this world.",
      "Let us become like Christ, since Christ became like us. Let us become gods because of Him, since He became man for us.",
      "He was baptized as man—but He remitted sins as God... He was tempted as man, but He conquered as God.",
      "What is not assumed is not healed; it is what is united to His divinity that is saved.",
      "The very fact that God is called 'Father' gives us the idea of the Son, and the name 'Son' gives us that of the Father.",
      "For the Son is the Counsel and Wisdom and Power of the Father. For this reason, too, He came into the world; and in the Creed, we confess that He was incarnate and made man.",
      "The Holy Spirit is called the Spirit of God, the Spirit of Christ, the Spirit of the Lord, the Spirit of adoption, of truth, of liberty; the Spirit of wisdom, of understanding, of counsel, of might, of knowledge, of godliness, of the fear of God.",
      "Let us not be content with only the name of Christians, but let us also have the reality. Let us not be satisfied with seeming to be something, but let us be what we are called.",
      "The Word himself came to you, becoming flesh for you, and he bore your infirmities, becoming like you, that you might become like him.",
      "Nothing is more characteristically Christian than being made perfect in weakness.",
      "The Son is the Father's Will."
    ],
    prayers:
      "O God, who were pleased to give light to your Church by the example and teaching of the Bishops Saint Basil the Great and Saint Gregory Nazianzen, grant, we pray, that in humility we may learn your truth and practice it faithfully in charity. Through our Lord Jesus Christ, your Son, who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    books: ["five-theological-orations", "autobiographical-poems", "letters"],
    is_dominican: false,
    is_doctor: true,
    rank: CelebrationRank.MEMORIAL,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },
  {
    id: "john-chrysostom",
    name: "St. John Chrysostom",
    feast_day: "09-13",
    short_bio: "Archbishop of Constantinople, renowned preacher, and Doctor of the Church",
    biography: [
      "St. John Chrysostom was born around 347 in Antioch, Syria, to a wealthy family. His father, a high-ranking military officer, died when John was young, and he was raised by his devout Christian mother, Anthusa.",
      "John received an excellent education in rhetoric from the pagan teacher Libanius, one of the most famous orators of his time. After his education, John was drawn to Christianity and was baptized around 368. He studied theology under Diodore of Tarsus and lived as a hermit for several years.",
      "Due to poor health from his austere ascetic practices, John returned to Antioch, where he was ordained a deacon in 381 and a priest in 386. For 12 years, he preached in Antioch's main church, gaining a reputation as an exceptional orator. His eloquence earned him the name 'Chrysostom,' meaning 'golden-mouthed.'",
      "In 397, John was appointed Archbishop of Constantinople. As archbishop, he reformed the clergy, cared for the poor, built hospitals, and spoke out against the lavish lifestyles of the wealthy and powerful, including Empress Eudoxia.",
      "His outspoken criticism of corruption and excess made him many enemies at court. In 403, a synod orchestrated by Theophilus of Alexandria and supported by Eudoxia deposed John on trumped-up charges. Though briefly reinstated, he was exiled again in 404 after criticizing the empress.",
      "John was forced to march to his place of exile in harsh conditions, which led to his death on September 14, 407, in Comana Pontica (modern-day Turkey). His last words were reportedly, 'Glory be to God for all things!'",
      "He was a prolific writer whose works include homilies on books of the Bible, treatises on the priesthood and Christian living, and liturgical texts. The Divine Liturgy of St. John Chrysostom is still the most commonly used liturgy in the Eastern Orthodox Church. He was declared a Doctor of the Church in 1568 by Pope Pius V.",
    ],
    image_url: "/saints/st-john-chrysostom.jpg",
    patronage: "Preachers, speakers, lecturers, Constantinople, epilepsy",
    birth_year: 347,
    death_year: 407,
    prayers:
      "O God, strength of those who hope in you, who willed that the Bishop Saint John Chrysostom should be illustrious by his wonderful eloquence and his experience of suffering, grant us, we pray, that, instructed by his teachings, we may be strengthened through the example of his invincible patience. Through our Lord Jesus Christ, your Son, who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    books: ["on-the-priesthood", "homilies-on-matthew", "homilies-on-romans"],
    quotes: [
      "If you cannot find Christ in the beggar at the church door, you will not find Him in the chalice.",
      "The road to Hell is paved with the bones of priests and monks, and the doors of Hell are held open by their bishops.",
      "The rich man is not one who is in possession of much, but one who gives much.",
      "A comprehended God is no God.",
      "When you are weary of praying and do not receive, consider how often you have heard a poor man calling upon you, and have not listened to him.",
      "No one can harm the man who does himself no wrong.",
      "Let us relieve the poverty of those that beg of us and let us not be over-exact about it.",
      "The bee is more honored than other animals, not because she labors, but because she labors for others.",
      "When you are before the altar where Christ reposes, you ought no longer to think that you are amongst men; but believe that there are troops of angels and archangels standing by you, and trembling with respect before the sovereign Master of Heaven and earth.",
      "The love of money is the root of all evils.",
      "The waters have risen and severe storms are upon us, but we do not fear drowning, for we stand firmly upon a rock. Let the sea rage, it cannot break the rock. The waves may strike the rock, but they cannot shatter it.",
      "The Holy Scriptures were not given to us that we should enclose them in books, but that we should engrave them upon our hearts.",
      "A comprehended God is no God.",
      "The road to Hell is paved with the bones of priests and monks, and the doors of Hell are held open by their bishops.",
      "The bee is more honored than other animals, not because she labors, but because she labors for others."
    ],
    is_dominican: false,
    is_doctor: true,
    rank: CelebrationRank.MEMORIAL,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },
  {
    id: "ephrem",
    name: "St. Ephrem the Syrian",
    feast_day: "06-09",
    short_bio: "Deacon, theologian, poet, and Doctor of the Church",
    biography: [
      "St. Ephrem was born around 306 in Nisibis, Mesopotamia (now Nusaybin, Turkey), to Christian parents. Little is known about his early life, but he was baptized as a young man and became a disciple of Bishop James of Nisibis.",
      "Ephrem served as a teacher and later as head of the theological school in Nisibis. When the city fell to the Persians in 363, he fled with many Christians to Edessa (modern-day Şanlıurfa, Turkey), where he continued his work as a teacher and deacon.",
      "In Edessa, Ephrem established a choir of women who sang hymns he had composed. He used poetry and music as tools for teaching theology and combating heresy, particularly Arianism and Gnosticism. His hymns were so popular that he was called 'The Harp of the Holy Spirit.'",
      "Ephrem was known for his ascetic lifestyle and deep devotion to the Virgin Mary. He never became a priest, preferring to remain a deacon throughout his life. He was also known for his charitable work, especially during a famine in Edessa when he organized relief efforts.",
      "He was a prolific writer, composing hymns, biblical commentaries, and theological treatises. His works are characterized by rich imagery, poetic beauty, and profound theological insights. He wrote primarily in Syriac, a dialect of Aramaic, the language Jesus spoke.",
      "During a famine in 373, Ephrem was actively caring for the sick when he contracted an illness himself. He died on June 9, 373, in Edessa. He was declared a Doctor of the Church by Pope Benedict XV in 1920, the only Syriac Father to receive this honor.",
    ],
    image_url: "/saints/st-ephrem.jpg",
    patronage: "Spiritual directors, Syriac Christians, hymnwriters",
    birth_year: 306,
    death_year: 373,
    prayers:
      "Pour into our hearts O Lord, we pray, the Holy Spirit, at whose prompting the Deacon Saint Ephrem exulted in singing of your mysteries and from whom he received the strength to serve you alone. Through our Lord Jesus Christ, your Son, who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    books: ["hymns-on-faith", "hymns-on-paradise", "commentary-on-diatessaron"],
    quotes: [
      "The hammers of the whole creation cannot break the rock of Christ.",
      "The Lord entered her and became a servant; the Word entered her, and became silent within her; thunder entered her and his voice was still; the Shepherd of all entered her; He became a Lamb in her, and came forth bleating.",
      "The keys of death are in His hand, and He opens and no man shuts, and shuts and no man opens.",
      "The Lord of all was under a woman's commands in Nazareth. Mary gave an order to the God of all creation as if He were her servant.",
      "The Lord went into the Jordan and was baptized. The Immortal One was baptized, and the One who purifies all was purified.",
      "The Lord of the heavens now let Himself be stripped by His enemies; He who holds the waters in His hands was bound by His captors.",
      "The One who is above all things was among us as one who serves, and He who is in the bosom of the Father has come to the servant's place.",
      "The Lord of all was among the dead as one of them, and in the tomb He was with the dead as the Giver of life.",
      "The Lord of the heights came down to the depths to seek out the lost sheep, and He carried it on His shoulders and brought it back to the heights.",
      "The Lord of all was baptized by John in the Jordan, and the voice of the Father bore witness to Him from on high.",
      "The Lord of all was led like a lamb to the slaughter, and like a sheep before its shearers He was silent and opened not His mouth.",
      "The Lord of all was crucified between two thieves, and He gave the kingdom to the one who believed in Him.",
      "The Lord of all was laid in a new tomb, and He made it a source of life for all who believe in Him.",
      "The Lord of all rose from the dead on the third day, and He appeared to His disciples and confirmed them in the faith.",
      "The Lord of all ascended into heaven and sat down at the right hand of the Father, and He will come again in glory to judge the living and the dead."
    ],
    is_dominican: false,
    is_doctor: true,
    rank: CelebrationRank.MEMORIAL,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },
  {
    id: "hilary-of-poitiers",
    name: "St. Hilary of Poitiers",
    feast_day: "01-13",
    short_bio: "Bishop of Poitiers, theologian, and Doctor of the Church",
    biography: [
      "St. Hilary was born around 310 in Poitiers, Gaul (modern-day France), to a wealthy pagan family. He received an excellent classical education and married, having at least one daughter, Saint Abra.",
      "Through his study of Scripture, particularly the Old and New Testaments, Hilary and his family converted to Christianity when he was in his 30s. His intelligence and devotion led to his election as Bishop of Poitiers around 353, despite being a married layman.",
      "Hilary's episcopate coincided with the height of the Arian controversy, which denied the full divinity of Christ. Though the Western Church largely remained orthodox, Emperor Constantius II supported Arianism and pressured bishops to condemn St. Athanasius, the champion of Nicene orthodoxy.",
      "When Hilary refused to condemn Athanasius at the Synod of Béziers in 356, the emperor exiled him to Phrygia in Asia Minor (modern-day Turkey). This exile, intended as punishment, actually broadened Hilary's theological understanding as he became familiar with Eastern theology and improved his Greek.",
      "During his exile, Hilary wrote his most important work, 'On the Trinity,' which defended the Nicene faith against Arianism. He also composed hymns, making him one of the first Latin hymn writers.",
      "In 360, Hilary was allowed to return to Poitiers, where he continued to fight against Arianism in Gaul and Italy. He organized synods, wrote theological works, and mentored St. Martin of Tours.",
      "Hilary died around 367 in Poitiers. He was declared a Doctor of the Church by Pope Pius IX in 1851, recognizing his significant contributions to Trinitarian theology and his role in defending orthodox Christianity in the West against Arianism.",
    ],
    image_url: "/saints/st-hilary-of-poitiers.jpg",
    patronage: "Lawyers, the sick, children with disabilities",
    birth_year: 310,
    death_year: 367,
    prayers:
      "Grant, we pray, almighty God, that we may rightly understand and truthfully profess the divinity of your Son, which the Bishop Saint Hilary taught with such constancy. Through our Lord Jesus Christ, your Son, who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    books: ["on-the-trinity", "commentary-on-matthew", "treatise-on-the-psalms"],
    is_dominican: false,
    is_doctor: true,
    rank: CelebrationRank.MEMORIAL,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },
  {
    id: "cyril-of-alexandria",
    name: "St. Cyril of Alexandria",
    feast_day: "06-27",
    short_bio: "Patriarch of Alexandria, defender of the title 'Mother of God,' and Doctor of the Church",
    biography: [
      "St. Cyril was born around 376 in Alexandria, Egypt, and was the nephew of Theophilus, Patriarch of Alexandria. He received a good education in theology and classics and became a monk for a time before being ordained a priest.",
      "When his uncle died in 412, Cyril succeeded him as Patriarch of Alexandria, one of the most important sees in the early Church. His early years as patriarch were marked by controversies with various groups, including Novatians, Jews, and pagans, sometimes involving regrettable violence.",
      "Cyril's most significant theological contribution came in his dispute with Nestorius, the Patriarch of Constantinople, who objected to the title 'Theotokos' (God-bearer or Mother of God) for the Virgin Mary. Nestorius preferred 'Christotokos' (Christ-bearer), arguing that Mary gave birth only to Christ's human nature.",
      "Cyril recognized that this position threatened the unity of Christ's person and the reality of the Incarnation. He wrote extensively against Nestorius, emphasizing that Christ is one person with two natures, divine and human, and therefore Mary could rightly be called the Mother of God.",
      "The controversy led to the Council of Ephesus in 431, where Cyril presided as Pope Celestine I's representative. The Council condemned Nestorius and affirmed the title 'Theotokos' for Mary, a decision that has remained central to both Eastern and Western Christianity.",
      "After the Council, Cyril worked to reconcile with the Antiochene theologians who had supported Nestorius. In 433, he accepted the Formula of Reunion, which maintained the condemnation of Nestorius while addressing some of the concerns of the Antiochene school.",
      "Cyril was a prolific writer, producing biblical commentaries, theological treatises, and letters. He died on June 27, 444, in Alexandria. He was declared a Doctor of the Church by Pope Leo XIII in 1882, recognizing his crucial role in defending the unity of Christ's person and the divine motherhood of Mary.",
    ],
    image_url: "/saints/st-cyril-of-alexandria.jpg",
    patronage: "Alexandria, Egypt",
    birth_year: 376,
    death_year: 444,
    prayers:
      "O God, who made the Bishop Saint Cyril of Alexandria an invincible champion of the divine motherhood of the most Blessed Virgin Mary, grant, we pray, that we, who believe she is truly the Mother of God, may be saved through the Incarnation of Christ your Son. Who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    books: ["against-nestorius", "commentary-on-john", "thesaurus"],
    is_dominican: false,
    is_doctor: true,
    rank: CelebrationRank.MEMORIAL,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },
  {
    id: "cyril-of-jerusalem",
    name: "St. Cyril of Jerusalem",
    feast_day: "03-18",
    short_bio: "Bishop of Jerusalem, catechist, and Doctor of the Church",
    biography: [
      "St. Cyril was born around 315 in or near Jerusalem. Little is known about his early life, but he received a good education in Scripture and the classics. He was ordained a deacon around 335 by Bishop Macarius of Jerusalem and a priest around 343 by Bishop Maximus.",
      "In 350, Cyril succeeded Maximus as Bishop of Jerusalem. His episcopate was difficult, marked by doctrinal disputes and political intrigue. He was exiled three times: first by the Arian Metropolitan Acacius of Caesarea (357-359), then by the Arian Emperor Constantius II (360-361), and finally by the Emperor Valens (367-378).",
      "Despite these challenges, Cyril was a dedicated pastor and teacher. He is best known for his 'Catechetical Lectures,' a series of 24 instructions given to catechumens preparing for baptism and to the newly baptized. These lectures provide valuable insight into the liturgical practices and doctrinal teachings of the Jerusalem Church in the 4th century.",
      "Cyril participated in the First Council of Constantinople in 381, which completed the Nicene Creed by affirming the divinity of the Holy Spirit. This Council also recognized Jerusalem as a patriarchate, giving it a status equal to Rome, Constantinople, Alexandria, and Antioch.",
      "Though sometimes suspected of semi-Arianism in his early career, Cyril's theology was firmly orthodox. He emphasized the reality of Christ's humanity and divinity, the value of the virginal conception, and the real presence of Christ in the Eucharist.",
      "Cyril died on March 18, 386, in Jerusalem, after serving as bishop for about 35 years. He was declared a Doctor of the Church by Pope Leo XIII in 1883, recognizing the importance of his catechetical writings for understanding the development of Christian doctrine and liturgy.",
    ],
    image_url: "/saints/st-cyril-of-jerusalem.jpg",
    patronage: "Jerusalem, catechists, catechumens",
    birth_year: 315,
    death_year: 386,
    prayers:
      "O God, who through the Bishop Saint Cyril of Jerusalem led your Church in a wonderful way to a deeper understanding of the mysteries of salvation, grant us, through his intercession, that we may so acknowledge your Son as to have life ever more abundantly. Through our Lord Jesus Christ, your Son, who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    books: ["catechetical-lectures", "mystagogical-catecheses", "letter-to-constantius"],
    is_dominican: false,
    is_doctor: true,
    rank: CelebrationRank.MEMORIAL,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },
  {
    id: "peter-chrysologus",
    name: "St. Peter Chrysologus",
    feast_day: "07-30",
    short_bio: "Bishop of Ravenna, preacher, and Doctor of the Church",
    biography: [
      "St. Peter Chrysologus was born around 406 in Imola, Italy. His name 'Chrysologus' means 'golden-worded,' a tribute to his exceptional preaching skills. Little is known about his early life, but he was educated under Bishop Cornelius of Imola, who ordained him a deacon.",
      "Around 433, Peter was appointed Bishop of Ravenna, then the capital of the Western Roman Empire, by Pope Sixtus III. According to tradition, his appointment came after St. Peter the Apostle appeared in a dream to both the Pope and Empress Galla Placidia, indicating that Peter should be chosen.",
      "As bishop, Peter worked to combat the remaining paganism in his diocese and to counter various heresies, particularly Monophysitism (which claimed Christ had only one nature) and Arianism (which denied Christ's full divinity). He was known for his orthodoxy, pastoral care, and especially for his clear, concise sermons.",
      "Peter was a friend of Pope Leo I (Leo the Great) and supported him in his defense of orthodox Christology against the Monophysite heresy. When Eutyches, the originator of Monophysitism, appealed to Peter for support after being condemned, Peter directed him to accept the teaching of Pope Leo.",
      "About 176 of Peter's homilies have survived, most of them brief explanations of Scripture readings or aspects of the Creed. They reveal his deep understanding of Scripture, his concern for his flock, and his ability to explain complex theological concepts in simple, vivid language.",
      "Peter died around 450 in his hometown of Imola, where he had returned due to failing health. He was declared a Doctor of the Church by Pope Benedict XIII in 1729, recognizing the theological depth and pastoral wisdom of his preaching.",
    ],
    image_url: "/saints/st-peter-chrysologus.jpg",
    patronage: "Preachers, homilists",
    birth_year: 406,
    death_year: 450,
    prayers:
      "O God, who made the Bishop Saint Peter Chrysologus an outstanding preacher of your incarnate Word, grant, through his intercession, that we may constantly ponder in our hearts the mysteries of your salvation and faithfully express them in what we do. Through our Lord Jesus Christ, your Son, who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    books: ["collected-sermons", "letters-on-the-incarnation", "homilies-on-the-gospels"],
    is_dominican: false,
    is_doctor: true,
    rank: CelebrationRank.MEMORIAL,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },
  {
    id: "leo-the-great",
    name: "St. Leo the Great",
    feast_day: "11-10",
    short_bio: "Pope, defender of orthodoxy, and Doctor of the Church",
    biography: [
      "St. Leo was born around 400, likely in Tuscany, Italy. Little is known about his early life, but he was well-educated and became a deacon of the Roman Church, serving under Pope Celestine I and Pope Sixtus III.",
      "As a deacon, Leo was already influential, corresponding with important figures like St. Cyril of Alexandria and John Cassian. In 440, while on a diplomatic mission to Gaul, he was elected Pope to succeed Sixtus III, and he was consecrated on September 29 of that year.",
      "Leo's pontificate (440-461) was marked by his efforts to centralize church administration, extend papal authority, and defend orthodox doctrine. He is known for his clear teaching on the two natures of Christ (divine and human) in one person, articulated in his famous 'Tome,' which was read at the Council of Chalcedon in 451.",
      "In 452, Leo personally met with Attila the Hun, who was threatening to invade Rome. The details of their meeting are not well-documented, but afterward, Attila withdrew his forces. Three years later, when the Vandals under Genseric sacked Rome, Leo's intervention prevented the burning of the city and the killing of its inhabitants.",
      "Leo was a prolific writer whose sermons and letters reveal his theological acumen and pastoral concern. His writings emphasize the primacy of the Roman See, the unity of the Church, and the importance of proper liturgical practice.",
      "He died on November 10, 461, in Rome and was buried in St. Peter's Basilica. He was the first pope to be buried there. He was declared a Doctor of the Church by Pope Benedict XIV in 1754, recognizing his significant contributions to the development of Church doctrine, especially regarding Christology.",
    ],
    image_url: "/saints/st-leo-the-great.jpg",
    patronage: "Popes, public speakers",
    birth_year: 400,
    death_year: 461,
    prayers:
      "O God, who never allow the gates of hell to prevail against your Church, firmly founded on the apostolic rock, grant her, we pray, that through the intercession of Pope Saint Leo, she may stand firm in your truth and know the protection of lasting peace. Through our Lord Jesus Christ, your Son, who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    books: ["letters", "sermons", "tome-to-flavian"],
    is_dominican: false,
    is_doctor: true,
    rank: CelebrationRank.MEMORIAL,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },
  {
    id: "isidore-of-seville",
    name: "St. Isidore of Seville",
    feast_day: "04-04",
    short_bio: "Archbishop of Seville, scholar, and Doctor of the Church",
    biography: [
      "St. Isidore was born around 560 in Cartagena, Spain, to a family of distinguished lineage. After the death of his parents, he was raised and educated by his older brother, St. Leander, who was the Archbishop of Seville.",
      "Under Leander's guidance, Isidore received an excellent education in Latin, Greek, Hebrew, and various sciences. He became well-versed in classical literature, law, medicine, and theology. His love of learning and books was extraordinary.",
      "Around 600, Isidore succeeded his brother as Archbishop of Seville. As archbishop, he continued the work of converting the Visigothic rulers from Arianism to orthodox Christianity, a process begun by Leander. He also worked to unify the liturgical practices of the Spanish Church.",
      "Isidore presided over several important councils, including the Fourth Council of Toledo in 633, which established uniform liturgical practices throughout Spain and enacted measures for the education of clergy. He also founded schools and promoted education throughout his diocese.",
      "He is best known for his encyclopedic work, 'Etymologies' (or 'Origins'), which attempted to compile all knowledge of his time. This work became one of the most used textbooks of the Middle Ages and preserved much classical learning that might otherwise have been lost.",
      "Besides 'Etymologies,' Isidore wrote numerous other works on theology, history, grammar, natural science, and cosmology. His writings show his concern for education and his desire to preserve and transmit knowledge.",
      "Isidore died on April 4, 636, in Seville. He was canonized by Pope Clement VIII in 1598 and declared a Doctor of the Church by Pope Innocent XIII in 1722. In 1999, Pope John Paul II named him the patron saint of the internet, computers, and computer users because of his efforts to catalog knowledge.",
    ],
    image_url: "/saints/st-isidore-of-seville.jpg",
    patronage: "Internet, computers, computer users, students, schoolchildren",
    birth_year: 560,
    death_year: 636,
    prayers:
      "Hear our prayers, O God, and grant that your Church, instructed by the teaching of Saint Isidore, Bishop and Doctor, may preserve in her heart the things she has received from heaven and express them in deeds of constant love. Through our Lord Jesus Christ, your Son, who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    books: ["etymologies", "on-church-offices", "history-of-the-goths"],
    is_dominican: false,
    is_doctor: true,
    rank: CelebrationRank.MEMORIAL,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },
  {
    id: "bede-the-venerable",
    name: "St. Bede the Venerable",
    feast_day: "05-25",
    short_bio: "Monk, scholar, historian, and Doctor of the Church",
    biography: [
      "St. Bede was born in 672 or 673 in Northumbria, England. At the age of seven, he was entrusted to the care of Benedict Biscop, the abbot of the monastery of St. Peter at Wearmouth. Later, he moved to the monastery's new foundation at Jarrow, where he spent the rest of his life.",
      "Bede was ordained a deacon at the unusually early age of 19 and a priest at 30. He devoted himself to the study of Scripture and to teaching and writing. He learned Latin, Greek, and Hebrew and had access to a fine library brought from Rome by Benedict Biscop.",
      "Despite never traveling beyond Northumbria, Bede became one of the most learned men of his time. He wrote about 40 books, covering history, chronology, lives of saints, commentaries on Scripture, treatises on grammar and natural phenomena, hymns, and poems.",
      "His most famous work is the 'Ecclesiastical History of the English People,' completed in 731, which is the primary source for understanding the conversion of the Anglo-Saxons to Christianity. In this work, Bede introduced the practice of dating events from the birth of Christ (AD/Anno Domini), which eventually became the standard system of dating in the Western world.",
      "Bede was known for his holiness of life, his diligence in study, and his clarity of thought. He was also a skilled teacher and had many students. His approach to scholarship, which emphasized the careful examination of sources and the reconciliation of apparent contradictions, was ahead of his time.",
      "He died on May 25, 735, at Jarrow, after dictating the final passage of his translation of the Gospel of John into Old English. His remains were later transferred to Durham Cathedral.",
      "Bede was declared a Doctor of the Church by Pope Leo XIII in 1899, the only native of Great Britain to receive this honor. He is often called 'The Venerable Bede,' a title that was already attached to his name by the 9th century, reflecting the high esteem in which he was held.",
    ],
    image_url: "/saints/st-bede-the-venerable.jpg",
    patronage: "Historians, scholars, English writers, lectors",
    birth_year: 673,
    death_year: 735,
    prayers:
      "O God, who bring light to your Church through the learning of the Priest Saint Bede, mercifully grant that your servants may always be enlightened by his wisdom and helped by his merits. Through our Lord Jesus Christ, your Son, who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    books: ["ecclesiastical-history", "lives-of-the-abbots", "commentary-on-acts"],
    is_dominican: false,
    is_doctor: true,
    rank: CelebrationRank.MEMORIAL,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },
  {
    id: "peter-damian",
    name: "St. Peter Damian",
    feast_day: "02-21",
    short_bio: "Cardinal, monk, reformer, and Doctor of the Church",
    biography: [
      "St. Peter Damian was born in 1007 in Ravenna, Italy, to a poor family. Orphaned at a young age, he was initially raised by an older brother who mistreated him. Later, another brother, a priest named Damian, took him in and provided for his education, which is why he took the name 'Damian' in gratitude.",
      "Peter studied at Ravenna, Faenza, and Parma, becoming a renowned teacher of rhetoric. Despite his success, he felt called to a more austere life and joined the hermitage of Fonte Avellana around 1035, where he embraced a life of prayer, fasting, and study.",
      "His intellectual abilities and spiritual depth led to his appointment as prior of Fonte Avellana in 1043. Under his leadership, the community grew, and he established five other hermitages. He also wrote a rule for the community that emphasized solitude, prayer, and self-discipline.",
      "Peter became a leading figure in the reform movement of the 11th century, which sought to address corruption and laxity in the Church. He wrote extensively against simony (the buying and selling of Church offices), clerical marriage, and other abuses.",
      "In 1057, despite his reluctance, Pope Stephen IX made him Cardinal-Bishop of Ostia. In this role, he served as a papal legate on various diplomatic missions and continued to advocate for Church reform. After Stephen's death, he supported the election of Pope Nicholas II and later Pope Alexander II against antipopes.",
      "Peter was a prolific writer whose works include letters, sermons, biographies of saints, and theological treatises. His most famous work, 'The Book of Gomorrah,' denounced sexual immorality among the clergy. He also wrote on spiritual topics, emphasizing the contemplative life and the importance of personal reform.",
      "In 1072, after returning from a papal mission to Ravenna, Peter fell ill and died on February 22 at the monastery of Santa Maria degli Angeli near Faenza. He was declared a Doctor of the Church by Pope Leo XII in 1828, recognizing his contributions to Church reform and spiritual theology.",
    ],
    image_url: "/saints/st-peter-damian.jpg",
    patronage: "Reformers, hermits",
    birth_year: 1007,
    death_year: 1072,
    prayers:
      "Grant us, we pray, almighty God, that we may so follow the teaching and example of the Bishop Saint Peter Damian, that, putting nothing before Christ and always ardent in the service of your Church, we may be led to the joys of eternal light. Through our Lord Jesus Christ, your Son, who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    books: ["book-of-gomorrah", "life-of-romuald", "letters"],
    is_dominican: false,
    is_doctor: true,
    rank: CelebrationRank.MEMORIAL,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },
  {
    id: "anselm",
    name: "St. Anselm of Canterbury",
    feast_day: "04-21",
    short_bio: "Archbishop of Canterbury, theologian, and Doctor of the Church",
    biography: [
      "St. Anselm was born in 1033 in Aosta, in the Kingdom of Burgundy (now part of Italy). His father, Gundulf, was a Lombard nobleman, and his mother, Ermenberga, was a pious woman who instilled in him a deep faith.",
      "As a young man, Anselm had a strained relationship with his father and left home at the age of 23. After three years of wandering through Burgundy and France, he arrived at the Benedictine abbey of Bec in Normandy, attracted by the reputation of its prior, Lanfranc.",
      "In 1060, Anselm entered the monastery at Bec, where he quickly distinguished himself for his intellectual abilities and spiritual depth. He became prior in 1063 when Lanfranc left to become abbot of Caen, and then abbot of Bec in 1078.",
      "Under Anselm's leadership, Bec became a center of learning, and his reputation as a theologian and spiritual director grew. He wrote several important philosophical and theological works during this period, including the 'Monologion,' 'Proslogion,' and 'Why God Became Man.'",
      "In 1093, Anselm was appointed Archbishop of Canterbury by King William II of England, though he initially resisted the appointment. His tenure as archbishop was marked by conflicts with both William II and his successor, Henry I, over the rights and independence of the Church.",
      "These conflicts led to Anselm's exile twice: from 1097 to 1100 and from 1103 to 1107. During these periods, he traveled to Rome and wrote some of his most important works. The disputes were eventually resolved with compromises on both sides.",
      "Anselm is known for his philosophical and theological contributions, particularly his ontological argument for the existence of God and his work on the atonement. He is often called the 'Father of Scholasticism' for his method of applying reason to illuminate faith.",
      "He died on April 21, 1109, in Canterbury. He was canonized in 1494 by Pope Alexander VI and declared a Doctor of the Church by Pope Clement XI in 1720.",
    ],
    image_url: "/saints/st-anselm.jpg",
    patronage: "Philosophers, theologians, Canterbury",
    birth_year: 1033,
    death_year: 1109,
    prayers:
      "O God, who led the Bishop Saint Anselm to seek out and teach the depths of your wisdom, grant, we pray, that our faith in you may so aid our understanding, that what we believe by your command may give delight to our hearts. Through our Lord Jesus Christ, your Son, who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    books: ["proslogion", "monologion", "why-god-became-man"],
    is_dominican: false,
    is_doctor: true,
    rank: CelebrationRank.OPTIONAL_MEMORIAL,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },
  {
    id: "bernard-of-clairvaux",
    name: "St. Bernard of Clairvaux",
    feast_day: "08-20",
    short_bio: "Abbot, reformer, mystic, and Doctor of the Church",
    biography: [
      "St. Bernard was born in 1090 near Dijon, France, to a noble family. His father was a knight and his mother, Aleth, was a woman of great piety who had a profound influence on his spiritual development.",
      "In 1113, at the age of 23, Bernard entered the monastery of Cîteaux, bringing with him about 30 companions, including his brothers and friends. Cîteaux was the motherhouse of the Cistercian Order, which had been founded in 1098 as a reform of Benedictine monasticism, emphasizing simplicity, manual labor, and strict observance of the Rule of St. Benedict.",
      "Just three years after his entry, Bernard was sent to establish a new monastery at Clairvaux. As abbot of Clairvaux, he led the community with wisdom and holiness, and the monastery flourished under his leadership. During his lifetime, he founded 68 monasteries throughout Europe.",
      "Bernard became one of the most influential figures of his time, involved in Church politics, theological disputes, and the preaching of the Second Crusade. He was a trusted advisor to popes, kings, and bishops, and his intervention was sought in various ecclesiastical and political matters.",
      "Despite his active involvement in worldly affairs, Bernard was fundamentally a contemplative who wrote extensively on spiritual topics. His sermons on the Song of Songs are considered masterpieces of mystical theology, and his devotion to the humanity of Christ and to the Virgin Mary had a lasting impact on Catholic spirituality.",
      "Bernard was also involved in theological controversies, most notably with Peter Abelard, whose rationalistic approach to theology he opposed. He was a strong defender of orthodox doctrine and played a key role in the condemnation of various heresies.",
      "He died on August 20, 1153, at Clairvaux. He was canonized by Pope Alexander III in 1174 and declared a Doctor of the Church by Pope Pius VIII in 1830. In 1953, Pope Pius XII issued an encyclical, 'Doctor Mellifluus,' commemorating the 800th anniversary of his death and highlighting his contributions to Catholic theology and spirituality.",
    ],
    image_url: "/saints/st-bernard-of-clairvaux.jpg",
    patronage: "Cistercians, beekeepers, candlemakers, Gibraltar",
    birth_year: 1090,
    death_year: 1153,
    prayers:
      "O God, who made the Abbot Saint Bernard a man consumed with zeal for your house and a light shining and burning in your Church, grant, through his intercession, that we may be on fire with the same spirit and walk always as children of light. Through our Lord Jesus Christ, your Son, who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    books: ["on-loving-god", "sermons-on-song-of-songs", "on-consideration"],
    is_dominican: false,
    is_doctor: true,
    rank: CelebrationRank.MEMORIAL,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },
  {
    id: "anthony-of-padua",
    name: "St. Anthony of Padua",
    feast_day: "06-13",
    short_bio: "Franciscan friar, preacher, and Doctor of the Church",
    biography: [
      "St. Anthony was born Fernando Martins de Bulhões in 1195 in Lisbon, Portugal, to a wealthy and noble family. At the age of 15, he entered the Augustinian community of Canons Regular at the Abbey of St. Vincent in Lisbon.",
      "After two years, he transferred to the Abbey of Santa Cruz in Coimbra, where he studied theology and Latin. He was ordained a priest around 1219 or 1220. While at Coimbra, he met Franciscan friars who were on their way to Morocco to preach to the Muslims.",
      "When the bodies of five Franciscans who had been martyred in Morocco were brought to Coimbra, Anthony was deeply moved and decided to join the Franciscan Order. He received permission to leave the Augustinians, joined the Franciscans, and took the name Anthony.",
      "Anthony also set out for Morocco to preach, but he became seriously ill and was forced to return. His ship was blown off course and landed in Sicily. From there, he made his way to Assisi, where he attended the Franciscan General Chapter in 1221 and met St. Francis of Assisi.",
      "Anthony's gifts as a preacher were discovered by chance when he was called upon to speak at an ordination ceremony. His eloquence and knowledge of Scripture impressed his superiors, who assigned him to preach against heresy in northern Italy and southern France.",
      "He became known as the 'Hammer of Heretics' for his effective preaching against the Cathars and Albigensians. He was also a renowned teacher of theology, the first in the Franciscan Order, and taught at the universities of Montpellier and Toulouse.",
      "In 1227, Anthony was appointed provincial superior of northern Italy. In 1228, he resigned this position to devote himself to preaching. He settled in Padua, where he preached his last and most famous series of sermons.",
      "Anthony died on June 13, 1231, at the age of 36, in Arcella, near Padua. He was canonized by Pope Gregory IX less than a year after his death, on May 30, 1232, one of the most quickly canonized saints in Church history. He was declared a Doctor of the Church by Pope Pius XII in 1946.",
    ],
    image_url: "/saints/st-anthony-of-padua.jpg",
    patronage: "Lost items, poor people, travelers, elderly, oppressed people, Padua, Portugal, Brazil",
    birth_year: 1195,
    death_year: 1231,
    prayers:
      "Almighty ever-living God, who gave Saint Anthony of Padua to your people as an outstanding preacher and an intercessor in their need, grant that, with his assistance, we may follow a life of Gospel perfection and know the help of your grace in every difficulty. Through our Lord Jesus Christ, your Son, who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    books: ["sermons-for-sundays", "sermons-for-feasts", "moral-concordances"],
    is_dominican: false,
    is_doctor: true,
    rank: CelebrationRank.MEMORIAL,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },
  {
    id: "lawrence-of-brindisi",
    name: "St. Lawrence of Brindisi",
    feast_day: "07-21",
    short_bio: "Capuchin friar, priest, theologian, and Doctor of the Church",
    biography: [
      "St. Lawrence was born Giulio Cesare Russo on July 22, 1559, in Brindisi, Kingdom of Naples (now in Italy). He was educated by the Conventual Franciscans in his hometown and later at the College of St. Mark in Venice. He was known for his exceptional intelligence and his ability to learn languages.",
      "In 1575, he joined the Capuchin Franciscans, taking the name Lawrence, and was ordained a priest in 1582. He completed his studies in theology, philosophy, the Bible, and several languages, including Latin, Greek, Hebrew, Syriac, French, and German.",
      "Lawrence's linguistic abilities made him an effective preacher throughout Europe. He was also a skilled theologian and wrote extensively, particularly in defense of the Catholic Church against Protestant reformers. His complete works fill 15 volumes.",
      "In 1599, he was appointed chaplain to the Imperial army in Hungary, where he played a crucial role in the victory over the Turks at Székesfehérvár in 1601. Riding on horseback and carrying only a crucifix, he led the Christian troops into battle and was credited with their victory.",
      "Lawrence held various leadership positions within the Capuchin Order, including provincial superior in Tuscany, Venice, and Switzerland, and definitor general (a high administrative position). He established Capuchin houses in Austria, Germany, and Bohemia.",
      "He also served as a diplomat for the Holy See and various Catholic rulers, undertaking missions to Germany, Spain, and Portugal. In 1619, he was sent to Spain by the people of Naples to plead their cause against the oppressive rule of the viceroy, but he died before completing this mission.",
      "Lawrence died on July 22, 1619, his 60th birthday, in Lisbon, Portugal. He was beatified by Pope Pius VI in 1783, canonized by Pope Leo XIII in 1881, and declared a Doctor of the Church by Pope John XXIII in 1959.",
    ],
    image_url: "/saints/st-lawrence-of-brindisi.jpg",
    patronage: "Brindisi, missionaries, preachers",
    birth_year: 1559,
    death_year: 1619,
    prayers:
      "O God, who for the glory of your name and the salvation of souls bestowed on the Priest Saint Lawrence of Brindisi a spirit of counsel and fortitude, grant, we pray, that in the same spirit, we may know what must be done and, through his intercession, bring it to completion. Through our Lord Jesus Christ, your Son, who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    books: ["mariale", "lutheranismi-hypotyposis", "explanatio-in-genesim"],
    is_dominican: false,
    is_doctor: true,
    rank: CelebrationRank.MEMORIAL,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },
  {
    id: "robert-bellarmine",
    name: "St. Robert Bellarmine",
    feast_day: "09-17",
    short_bio: "Jesuit, Cardinal, theologian, and Doctor of the Church",
    biography: [
      "St. Robert Bellarmine was born Roberto Francesco Romolo Bellarmino on October 4, 1542, in Montepulciano, Tuscany, Italy. His mother, Cinthia Cervini, was a sister of Pope Marcellus II. Despite his family's noble status, they were relatively poor.",
      "Robert received his early education from the Jesuits in Montepulciano. In 1560, against his father's wishes, he joined the Society of Jesus (the Jesuits). He studied philosophy at the Roman College (now the Pontifical Gregorian University) and then taught humanities at various Jesuit schools in Italy.",
      "After studying theology at the University of Padua and Leuven, he was ordained a priest in 1570. He became the first Jesuit professor at the University of Leuven, where he taught theology and gained a reputation as a skilled teacher and defender of the Catholic faith against Protestant teachings.",
      "In 1576, Pope Gregory XIII appointed him to teach controversial theology (apologetics) at the Roman College. During this time, he wrote his most famous work, 'Disputations on the Controversies of the Christian Faith,' a comprehensive defense of Catholic doctrine against Protestant objections.",
      "Robert held various administrative positions within the Jesuit order and the Church. In 1599, Pope Clement VIII made him a Cardinal, saying, 'The Church of God has not his equal in learning.' He served as Archbishop of Capua from 1602 to 1605, where he implemented the reforms of the Council of Trent.",
      "After returning to Rome in 1605, he continued to serve the Church in various capacities. He was involved in several significant controversies of his time, including the Galileo affair and disputes over papal authority. Despite his defense of papal power, he maintained that the pope's temporal authority was limited.",
      "Robert was known for his simple lifestyle, charity to the poor, and personal holiness. He wrote several catechisms and devotional works in addition to his theological treatises. He died on September 17, 1621, in Rome. He was canonized by Pope Pius XI in 1930 and declared a Doctor of the Church in 1931.",
    ],
    image_url: "/saints/st-robert-bellarmine.jpg",
    patronage: "Catechists, catechumens, canon lawyers, Bellarmine University",
    birth_year: 1542,
    death_year: 1621,
    prayers:
      "O God, who adorned the Bishop Saint Robert Bellarmine with wonderful learning and virtue to defend the faith of your Church, grant, through his intercession, that in the integrity of that same faith your people may always find joy. Through our Lord Jesus Christ, your Son, who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    books: ["disputations-on-controversies", "art-of-dying-well", "mind's-ascent-to-god"],
    is_dominican: false,
    is_doctor: true,
    rank: CelebrationRank.MEMORIAL,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },
  {
    id: "alphonsus-liguori",
    name: "St. Alphonsus Liguori",
    feast_day: "08-01",
    short_bio: "Bishop, founder of the Redemptorists, and Doctor of the Church",
    biography: [
      "St. Alphonsus was born on September 27, 1696, in Marianella, near Naples, Italy, to a noble family. He was a child prodigy who earned doctorates in both civil and canon law by the age of 16 and became a highly successful lawyer.",
      "In 1723, after losing an important case due to overlooking a key document, Alphonsus experienced a profound disillusionment with his legal career. He heard an interior voice saying, 'Leave the world and give yourself to me.' He abandoned law and, despite his father's opposition, began studying for the priesthood.",
      "Alphonsus was ordained a priest in 1726. He devoted himself to working with the poor and marginalized in Naples, particularly the 'lazzaroni' (street people). His gentle approach to confession and moral theology emphasized God's mercy rather than harsh judgment.",
      "In 1732, while resting in the mountains near Scala, Alphonsus had a vision of the spiritual abandonment of the rural poor. This led him to found the Congregation of the Most Holy Redeemer (the Redemptorists) in 1732, dedicated to missionary work among the rural poor.",
      "Alphonsus was a prolific writer whose works on moral theology, spirituality, and Mariology have had a lasting impact on the Church. His most famous works include 'The Glories of Mary,' 'The Practice of the Love of Jesus Christ,' and 'Moral Theology.'",
      "In 1762, despite his reluctance and poor health, Alphonsus was appointed Bishop of Sant'Agata dei Goti. As bishop, he reformed the diocese, established seminaries, and continued to write. He resigned his see in 1775 due to severe rheumatism that left him paralyzed and almost blind.",
      "The last years of his life were marked by physical suffering, spiritual trials, and conflicts within the Redemptorist congregation. He died on August 1, 1787, at Pagani, near Salerno. He was canonized in 1839 by Pope Gregory XVI and declared a Doctor of the Church by Pope Pius IX in 1871.",
    ],
    image_url: "/saints/st-alphonsus-liguori.jpg",
    patronage: "Confessors, moral theologians, vocations, arthritis sufferers",
    birth_year: 1696,
    death_year: 1787,
    prayers:
      "O God, who constantly raise up in your Church new examples of virtue, grant that we may follow so closely in the footsteps of the Bishop Saint Alphonsus in his zeal for souls as to attain the same rewards that are his in heaven. Through our Lord Jesus Christ, your Son, who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    books: ["moral-theology", "glories-of-mary", "practice-of-love-of-jesus-christ"],
    is_dominican: false,
    is_doctor: true,
    rank: CelebrationRank.MEMORIAL,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },
  {
    id: "peter-canisius",
    name: "St. Peter Canisius",
    feast_day: "12-21",
    short_bio: "Jesuit priest, theologian, and Doctor of the Church",
    biography: [
      "St. Peter Canisius was born Pieter Kanis on May 8, 1521, in Nijmegen, Netherlands, to a wealthy and prominent family. His father was Jacob Kanis, a successful businessman who served as mayor of Nijmegen.",
      "Peter received an excellent education, studying at the University of Cologne, where he earned a master's degree in 1540. While at Cologne, he met St. Peter Faber, one of the original companions of St. Ignatius of Loyola, who guided him through the Spiritual Exercises.",
      "In 1543, Peter became the first Dutchman to join the Society of Jesus (the Jesuits). After completing his theological studies, he was ordained a priest in 1546. He participated in the Council of Trent and was sent by St. Ignatius to teach at the University of Ingolstadt in Germany.",
      "Peter spent most of his life working in Germany, Austria, and Switzerland during the height of the Protestant Reformation. He founded colleges, advised emperors and princes, and worked tirelessly to strengthen the Catholic faith through preaching, teaching, and writing.",
      "He is best known for his three catechisms, written in 1555-58, which clearly explained Catholic doctrine in a time of religious confusion. His 'Summary of Christian Doctrine' became one of the most popular Catholic catechisms and was translated into 15 languages during his lifetime.",
      "Peter was also a prolific writer of letters, with over 1,400 surviving today. He edited and published the works of several Church Fathers and other significant Catholic writers. His diplomatic skills helped preserve Catholicism in many parts of Germany and Central Europe.",
      "Despite his many administrative and diplomatic responsibilities, Peter remained a man of deep prayer and humility. He often traveled on foot, visiting villages and towns to preach and teach. Despite facing opposition and threats, he maintained a gentle approach that earned him respect even from his opponents.",
      "After decades of tireless work, Peter's health began to fail. He suffered a stroke in 1591 and died on December 21, 1597, in Fribourg, Switzerland. He was beatified by Pope Pius IX in 1864, canonized by Pope Pius XI in 1925, and declared a Doctor of the Church by Pope Pius XI in 1925, recognizing his exceptional contributions to Catholic education and his role in preserving the Catholic faith in German-speaking lands during the Reformation.",
    ],
    image_url: "/saints/st-peter-canisius.jpg",
    patronage: "Germany, Catholic press, catechists, educators",
    birth_year: 1521,
    death_year: 1597,
    prayers:
      "O God, who for the defense of the Catholic faith made the Priest Saint Peter Canisius strong in virtue and in learning, grant, through his intercession, that those who seek the truth may joyfully find you, their God, and that your faithful people may persevere in confessing you. Through our Lord Jesus Christ, your Son, who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    books: ["catechisms", "de-verbi-dei-corruptelis", "notes-on-scripture"],
    is_dominican: false,
    is_doctor: true,
    rank: CelebrationRank.MEMORIAL,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },
  {
    id: "john-damascene",
    name: "St. John of Damascus",
    feast_day: "12-04",
    short_bio: "Priest, monk, theologian, and Doctor of the Church",
    biography: [
      "St. John was born around 675 in Damascus, Syria, to a wealthy Christian family. His father, Sergius Mansur, was a high official in the court of the Muslim caliph. John received an excellent education in philosophy, theology, and music from a Sicilian monk named Cosmas, whom his father had ransomed from slavery.",
      "John succeeded his father in his position at the court and served as a high official under the caliph. However, when Emperor Leo III the Isaurian began his campaign against sacred images (iconoclasm) around 726, John used his position to defend the veneration of icons, writing several treatises on the subject.",
      "According to tradition, Leo, unable to punish John directly because he lived under Muslim rule, forged a letter in which John appeared to be offering to betray Damascus to the Byzantines. The caliph, believing the forgery, had John's right hand cut off. John prayed before an icon of the Virgin Mary, and his hand was miraculously restored.",
      "After this event, John resigned his position and distributed his wealth to the poor. He entered the monastery of St. Sabas near Jerusalem, where he was ordained a priest and spent the rest of his life in prayer, writing, and theological study.",
      "John's most important work is 'The Fountain of Knowledge,' which includes 'The Dialectic' (on logic), 'On Heresies' (a history of heresies), and 'An Exact Exposition of the Orthodox Faith' (a systematic presentation of Christian doctrine). This last part became a standard textbook of Eastern Orthodox theology.",
      "He also wrote hymns and liturgical poetry that are still used in Eastern Christian liturgies. His defense of icons, based on the Incarnation of Christ, was influential at the Second Council of Nicaea (787), which definitively affirmed the legitimacy of venerating sacred images.",
      "John died around 749 at the monastery of St. Sabas. He was declared a Doctor of the Church by Pope Leo XIII in 1890, recognizing his significant contributions to theology, particularly his defense of sacred images and his systematic presentation of Christian doctrine.",
    ],
    image_url: "/saints/st-john-damascene.jpg",
    patronage: "Pharmacists, icon painters, theology students",
    birth_year: 675,
    death_year: 749,
    prayers:
      "Grant, we pray, O Lord, that we may be helped by the prayers of the Priest Saint John Damascene, so that the true faith, which he excelled in teaching, may always be our light and our strength. Through our Lord Jesus Christ, your Son, who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    books: ["fountain-of-knowledge", "on-holy-images", "sacred-parallels"],
    is_dominican: false,
    is_doctor: true,
    rank: CelebrationRank.MEMORIAL,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },
  {
    id: "hildegard-of-bingen",
    name: "St. Hildegard of Bingen",
    feast_day: "09-17",
    short_bio: "Benedictine abbess, mystic, composer, and Doctor of the Church",
    biography: [
      "St. Hildegard was born in 1098 in Bermersheim, near Alzey, in the Holy Roman Empire (modern-day Germany), the tenth child of a noble family. From an early age, she experienced mystical visions, though she kept them private for many years.",
      "At the age of eight, she was entrusted to the care of Jutta, an anchoress (religious recluse) at the Benedictine monastery in Disibodenberg. Hildegard was educated by Jutta and eventually joined the Benedictine order, making her religious profession around 1115.",
      "When Jutta died in 1136, Hildegard was elected magistra (leader) of the small women's community. As her reputation for wisdom and holiness grew, so did the number of women joining the community. In 1147, she founded a new monastery at Rupertsberg, near Bingen, where she served as abbess.",
      "Around 1150, Hildegard began to record her visions with the encouragement of her spiritual advisor, the monk Volmar, and the approval of Pope Eugenius III. Her first major work, 'Scivias' (Know the Ways of the Lord), describes 26 visions dealing with the relationship between God and humanity, the Church, and the redemption.",
      "Hildegard was extraordinarily multitalented. Besides her theological writings, she composed music, wrote plays, created an alternative alphabet, developed her own language, and wrote works on natural history and medicine. Her musical compositions, including the 'Ordo Virtutum' (Play of the Virtues), are still performed today.",
      "She was also a correspondent with popes, emperors, kings, and other notable figures of her time. She undertook four preaching tours throughout the German lands, which was highly unusual for a woman in the 12th century. She was not afraid to criticize clergy and secular rulers for their failings.",
      "Hildegard died on September 17, 1179, at her abbey in Rupertsberg. Though venerated as a saint locally, she was never formally canonized until 2012, when Pope Benedict XVI extended her liturgical cult to the universal Church. In the same year, he declared her a Doctor of the Church, recognizing her significant contributions to theology, music, medicine, and natural science.",
    ],
    image_url: "/saints/st-hildegard-of-bingen.jpg",
    patronage: "Musicians, writers, linguists, natural scientists, Germany",
    birth_year: 1098,
    death_year: 1179,
    prayers:
      "O God, by whose grace your servant Hildegard, kindled with the Fire of your love, became a burning and shining light in your Church: Grant that we also may be aflame with the spirit of love and discipline, and walk before you as children of light; through Jesus Christ our Lord, who lives and reigns with you, in the unity of the Holy Spirit, one God, now and for ever. Amen.",
    books: ["scivias", "liber-vitae-meritorum", "liber-divinorum-operum"],
    is_dominican: false,
    is_doctor: true,
    rank: CelebrationRank.MEMORIAL,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },
  {
    id: "gregory-of-narek",
    name: "St. Gregory of Narek",
    feast_day: "02-27",
    short_bio: "Armenian monk, poet, mystical theologian, and Doctor of the Church",
    biography: [
      "St. Gregory was born around 951 in the village of Andzevatsik in the historical Armenian region of Vaspurakan (now part of eastern Turkey). He was the son of Khosrov Andzevatsi, a theologian who served as archbishop of the region.",
      "After his mother's death, Gregory and his brother were educated by their maternal cousin, Anania of Narek, who was the founder and abbot of the monastery of Narek on the shores of Lake Van. Gregory eventually joined the monastery as a monk and was ordained a priest.",
      "Gregory spent most of his life at the monastery of Narek, where he gained a reputation as a teacher, poet, and theologian. He lived during a time of significant religious tension in Armenia, with pressure from both Byzantine Orthodox Christians and Muslims.",
      "His masterpiece is the 'Book of Lamentations,' also known as 'Narek,' a collection of 95 mystical prayers or odes in which he expresses his profound sense of human frailty and his longing for God. This work is considered one of the greatest works of Armenian literature and has been translated into many languages.",
      "Gregory also wrote biblical commentaries, panegyrics on the Virgin Mary and the Apostles, and liturgical hymns that are still used in the Armenian Church. His writings are characterized by their rich imagery, emotional depth, and theological insight.",
      "Despite some theological differences between the Armenian Apostolic Church and the Catholic Church, Gregory's works have been appreciated by both traditions for their spiritual depth and theological richness. He is one of the few saints venerated in both the Armenian Apostolic Church and the Catholic Church.",
      "Gregory died around 1003 at the monastery of Narek. He was declared a Doctor of the Church by Pope Francis on April 12, 2015, becoming the first Armenian and the 36th Doctor of the Church. This recognition highlights the ecumenical significance of his work and his contribution to the spiritual heritage of all Christians.",
    ],
    image_url: "/saints/st-gregory-of-narek.jpg",
    patronage: "Armenia, poets, musicians, those suffering from mental illness",
    birth_year: 951,
    death_year: 1003,
    prayers:
      "O God, who bestowed on the Priest Saint Gregory of Narek the grace to express in words of fire your ineffable greatness and your mercy without limit, grant that, through his intercession, we may become living prayers and witnesses of your love in the world. Through our Lord Jesus Christ, your Son, who lives and reigns with you in the unity of the Holy Spirit, one God, for ever and ever. Amen.",
    books: ["book-of-lamentations", "commentary-on-song-of-songs", "panegyric-on-the-virgin"],
    is_dominican: false,
    is_doctor: true,
    rank: CelebrationRank.MEMORIAL,
    color: LiturgicalColor.WHITE,
    proper: "Proper of Saints",
  },
]
